### ISSUE TITLE
Establish a Governance Board and/or Steering Committee

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/community#113]
As the Keptn project grows, a steering committee should be installed to shape the future of the Keptn project.

### Responsibilities of a steering committee member should include

- Own the overall charter, vision, and direction of the project
- Promote broad adoption of the overall project
- Provide guidance for the project maintainers
- Approving and prioritizing new Keptn integrations
- Archiving integrations or repositories of the Keptn organization and the ecosystem repositories
- Manage membership of Keptn organization
- Actively participate in the steering committee meetings

The process to build the steering committee can be aligned to other CNCF projects, such as the Steering Committee definition of [Crossplane](https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#steering-committee), or others.

### Seats

Steering committee seats should be limited, granted only for a period of time, and spread across multiple organizations.

### Election Process

Initial voting for steering committee members is should be open to all project maintainers. Nomination criteria have to be defined.

https://github.com/keptn/community/issues/113#tasklist-block-0ef8bf1d-867b-4d99-b7fd-0aab8adc6ece

**Comment by DavidPHirsch** [comment]
Governance committee has been set up
