### ISSUE TITLE
Add Keptn Emoji to branding directory and Slack

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#122]
This is a follow-up to the conversation with @mowies who created a bunch of Keptn emojis for the Dynatrace Slack, I think it would be awesome to update Slack and also to have emojis available in this repo.

![image](https://user-images.githubusercontent.com/3000480/158361754-6e918bd6-cbd5-4698-8c74-3179140d27f1.png)

## Acceptance criteria

- Generate emojis using https://makeemoji.com/ . Make sure to use Keptn PNG with a transparent background
- Create a new emoji folder in https://github.com/keptn/community/tree/main/branding and upload all nice images via a a pull request
- Ping @oleg-nenashev so that he adds emojis to Slack

**Comment by subhamgcon** [comment]
Hey @oleg-nenashev, Can I work on this issue?
