### ISSUE TITLE
Adopt Keptn Sockshop repository as a demos/examples GitHub org

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#124]
### Proposal

Keptn Sockshop GitHub org includes two GitHub repositories used in Keptn widely for tutorials and demos. Would be nice to have them within the Keptn organization officially.

- [x] Grant @oleg-nenashev ownership so that he can manage the repo
- [x] Update branding and repo metadata
- [ ] Rename the GitHub organization, testing is needed
- [ ] Update links to the repositories in the documentation
- [ ] Add the GitHub org to the community documentation
- [ ] TBD: Migrate https://github.com/keptn/examples (decision is needed, rather no than yes)

### References

* https://github.com/keptn-sockshop
* Slack coordination: https://keptn.slack.com/archives/CFH319TPE/p1647297632844219
* Logo:

![Keptn-demo](https://user-images.githubusercontent.com/3000480/158373323-7d5db9be-b676-4d4a-a889-919e2c5facd3.png)

### Sponsors

- @christian-kreuzberger-dtx 
- @johannes-b 
- @thisthat 

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thisthat** [comment]
After log4j we decided to abandon this idea
