### ISSUE TITLE
REQUEST: New membership for Raffy23

### ISSUE THREAD

**Issue by Raffy23** [keptn/community#126]
### GitHub Username

@Raffy23

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR
### Requirements (for approver, if applicable)

- [ ] I am a reviewer of the codebase for at least 1 month
- [ ] I am a reviewer for/or author of substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g., refactors/adds new functionality rather than one-line changes).
- [ ] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project approver](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Requirements (for maintainer, if applicable)

- [ ] I have deep understanding of the technical goals and direction of the subproject
- [ ] I have deep understanding of the technical domain (specifically the language) of the subproject
- [ ] I did sustained contributions to design and direction by doing all of:
  - [ ] I am authoring and reviewing proposals
  - [ ] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [ ] I am identifying subtle or complex issues in designs and implementation PRs
- [ ] I am directly contributing to the subproject through implementation and / or review
- [ ] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [ ] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

@thisthat
@christian-kreuzberger-dtx

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
    - keptn/gh-automation/pull/15
    - keptn-contrib/job-executor-service/pull/193
    - keptn-contrib/prometheus-service/pull/282
- Issues responded to
- SIG projects I am involved with
    - keptn-sandbox/keptn-service-template-go
    - keptn-contrib/prometheus-service
    - keptn-contrib/job-executor-service

**Comment by christian-kreuzberger-dtx** [comment]
I support

**Comment by thisthat** [comment]
I support

**Comment by thisthat** [comment]
I sent you an invitation @Raffy23! Welcome aboard 😄
