### ISSUE TITLE
Docs: Bootstrap quick start tutorials for `keptn` CD scenarios in real envirorment using `katacoda` platform

### ISSUE THREAD

**Issue by afzal442** [keptn/community#127]
### Proposal

Katacoda is an Interactive Learning and Training Platform for Software Engineers to help learn new technologies using real environments right in the browser. It helps empowering developers to learn the technologies such as Kubernetes, Machine Learning and cloud platforms using self-paced labs.
The power of cluster deployment, 😄 

Workable demo link: https://www.katacoda.com/cloudhks/scenarios/k3s

#### As discussed in the community call, Christian and Oleg brought some good points 💯 

- Katacoda, being an standalone service, provides you one step ahead access to use cases of any tool that you want to be familiar in order to test out the feature.
- Keptn acts a control plane which orchestrates the CD pipelines to perform testing against your deployed software and provide automatic [SLI/SLO based feedback](https://tutorials.keptn.sh/?cat=full-tour), could be accessed via cloud events API using its bridge /dashboard.
- Advanced usage is required to have but we can work apparently
- Need e2e and automation test before jumping on use cases with new releases of version
- Agree with `katacoda` outage and internet provider issues in case of timeouts in the console until blocked -> Soln. Try refreshing the page or connect high speed internet

#### Issues with tutorial to be addressed

- [ ] Helm-service and Jmeter-service test (Advanced Installation)
- [x] Promotheus
- [ ] Dynatrace Integration

####  Why `katacoda` ?

- [x] For better UX compatibility
- [x] For running workshop, inspired by Getting started with `Istio` workshop

### References
- https://keptn.sh/docs/quickstart/
- https://tutorials.keptn.sh/

Inspired by
- https://www.katacoda.com/courses/kubernetes
- https://learning.kasten.io/kubernetes/resources/
- https://layer5.io/learn/service-mesh-labs

**Comment by afzal442** [comment]
Hi,
Any thoughts or feedback here? 😃 

cc: @christian-kreuzberger-dtx @StackScribe @agardnerIT @oleg-nenashev

**Comment by christian-kreuzberger-dtx** [comment]
I'd love to see an easier way for the quickstart. If Katacoda is the way to go, we can try it out.

IMO we should provide multiple ways:

* Managed (Using Katacoda) - this will be a "I just want to try it out" experience
* Self-Owned (e.g., using K3d) - this will be a "I want to tinker with Kubernetes and learn a bit more" experience

**Comment by afzal442** [comment]
Thanks @christian-kreuzberger-dtx for your suggestion.
> we should provide multiple ways

Yes, on the long term, we will provide users to experience the playground with different cloud native infrastructure.

**Comment by agardnerIT** [comment]
I love the promise of Katacoda, that, to me, isn't the "problem", I'm all for people experiencing Keptn is as many (any ways) they see fit.

For me, the prerequisite to this issue is: https://github.com/keptn/keptn/issues/7176 - a slimmer Keptn install means faster startup for all rollout options.

**Comment by RAMESSESII2** [comment]
Hey @afzal442 🖖🏼, I believe Katacoda will be a great way for someone new to get the *gist* of the Keptn. 
I've been working on all sorts of cloud-native projects, and would like to develop the Katacoda scenarios for this project, maybe as a part of GSOC🙃. Can you get me started with this and hope you're still open to proposals 🤔.

**Comment by afzal442** [comment]
That's great @RAMESSESII2 . 
> Can you get me started with this and hope you're still open to proposals?

Are you on slack? You can follow [these](https://keptn.slack.com/archives/C033WCZFMAR/p1649156161163169?thread_ts=1649143676.341959&cid=C033WCZFMAR) comments posted on slack channel.

**Comment by agardnerIT** [comment]
This is very old but since we now have Killercoda - that @afzal442 was instrumental in getting up and running, believe this can be closed.
