### ISSUE TITLE
REQUEST: New membership for sarahhuber001

### ISSUE THREAD

**Issue by sarahhuber001** [keptn/community#146]
### GitHub Username

sarahhuber001

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR
### Requirements (for approver, if applicable)

- [ ] I am a reviewer of the codebase for at least 1 month
- [ ] I am a reviewer for/or author of substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g., refactors/adds new functionality rather than one-line changes).
- [ ] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project approver](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

Moritz Wiesinger, @mowies, Dynatrace
Anna Reale, @RealAnna, Dynatrace

### List of contributions to the Keptn project
- [Issue #7578](https://github.com/keptn/keptn/issues/7578)
- [PR #7683](https://github.com/keptn/keptn/pull/7683)
- [PR review #7529](https://github.com/keptn/keptn/pull/7529)

**Comment by mowies** [comment]
I support!

**Comment by oleg-nenashev** [comment]
I support

**Comment by thisthat** [comment]
Invitation sent! Welcome aboard @sarahhuber001  🙌
