### ISSUE TITLE
Keptn at Kubecon North America, 2022

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#155]
We're going to participate in Kubecon! This is a ticket for prepwork and links

## References

- [Planning Document](https://docs.google.com/document/d/1x7gnqWAbxSr55IgmrT0wSJ6sh5KMoWfZvD2G-8U6_t8/edit?usp=sharing)

## Scope

- Talks during the main tracks
- Project office hours
- Keptn community day
- Satellite events, e.g. GitOps Summit
- Bug bash

**Comment by oleg-nenashev** [comment]
CC @bradmccoydev @grabnerandi @thschue who were on the planned program committee for Kubecon Valencia

**Comment by thschue** [comment]
As described in the planning document, I requested an in-person kiosk and virtual project office hours.

**Comment by thschue** [comment]
> As described in the planning document, I requested an in-person kiosk and virtual project office hours.

Got a response:

_Thank you for submitting your form for Project Benefits at KubeCon + CloudNativeCon North America 2022!  I can confirm that we have received the submission from you for Keptn. I see that you have requested Virtual Project Office Hours + In-Person Kiosk. At this time, the Virtual Project Office Hours benefit is only available to projects that are unable to attend the event in person. Kindly let us know if you will be joining us in person and hosting an in-person kiosk OR if you will be joining us virtually and hosting virtual project office hours._

Responded that we're participating in person and would like to host a kiosk.

**Comment by oleg-nenashev** [comment]
UPD: Keptn Community Day is confirmed for Oct 25. It will be a full-day event if we manage to fill the agenda 

* Website landing: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#keptn-community-day
* CFP form: https://docs.google.com/forms/d/e/1FAIpQLSdXtR1htz6rID2FUOvqKeN51zla9scZlAbFSW9GflmpqjU-0w/viewform

**Comment by thschue** [comment]
As KubeCon NA has passed, this will be closed
