### ISSUE TITLE
Regarding Open Source Summit registration

### ISSUE THREAD

**Issue by mehabhalodiya** [keptn/community#158]
**Please also provide the details whether you give a talk or plan to participate in other activities at the conference. If there is something related to Keptn, it would be great to get it mentioned too.**

As I missed the CFP for this conference, so not going as a speaker right now but yes, I will get to:
- Network with 2,000 open source developers and technologists from across the globe to collaborate, share information, gain insights, solve technical problems, and further innovation. 
- Participate in an unparalleled hallway track - run into key project maintainers and community leaders around every corner. Also, I will gain practical insights in [sessions](https://email.linuxfoundation.org/e3t/Ctc/RI+113/cZw--04/VVw6JG4b5n8PW10tHkL6-CK3qW6L2xF54N0nzqN1TFhvp3lLBZV1-WJV7CgY31W60k-4N6Q_0BTW7Qn-rl1ZZX5lW5757jc1stwM7THgFH6nwFTLW1qGp-Y8nPn-dW45ZXrb8kjtKXW3sNRsN5TyTCgN6BLpb2mxCjrW7ylX9l3CQmwWN8zjN1pxRMMtW49V_G92fWT2vW2hL3FM6_gb_CW39vNGf7cD_7RW9bNGGh3RcwK3W7x_yMB9gSJtpW6wpB5_4mCTGrW5dKgvQ2hJXkYW6QVkgW3bmk9lVkn0Nz6Nbf75N3jtmBXS-qkXW6f9S5F3SQRZbW7mY7-x4cytCbW3Ps0p18rDqHyW2hT2J11KS3xJN4d9Gm55KTY-W2ySYX282KZ513jWV1) covering the most critical and emerging topics and technologies across open source, brought to us by open source experts from around the globe. 
- Talk to speakers directly, and get a deeper understanding of what they’re sharing.

Currently, I don't know that how I can represent Keptn over there. But yes, happy to do that, if you can guide me, give me some ideas.

This is being submitted as I wanted to get the conference in-person ticket. I am a student and so I come under the `Academic` category. Hence, I would require $275 to get my conference registration done. The below snapshot is of the rates of it:

![Screenshot from 2022-07-28 21-52-38](https://user-images.githubusercontent.com/73488906/181617695-584c0f62-cf24-43f4-8f46-078113dc61f5.png)

Also, I make sure that my Travel Fund Request is approved and all the airfare and accommodations is being provided by the Linux Foundation.  Reference below:

![Screenshot from 2022-07-28 21-19-49](https://user-images.githubusercontent.com/73488906/181618475-9c80d3c9-e850-4827-b23f-1f307e438533.png)

Thank you ❤️

**Comment by oleg-nenashev** [comment]
I'm definitely plus one for this request. 275 EUR is a reasonable price, and I will find a way to get it funded. Please consider it approved, and let me know if any additional steps and paperwork are needed for your visa application

Just a heads up, I think we have a solution that won't even require money.

**Comment by mehabhalodiya** [comment]
Thank you so much, Oleg, for your heads up on this!
Also, to @fdegir, can't thank you enough to expedite the process of my ticket. Looking forward!

![Screenshot from 2022-07-29 23-32-16](https://user-images.githubusercontent.com/73488906/181818393-512bfe51-5449-4905-a194-c146ef568cee.png)
