### ISSUE TITLE
REQUEST: New membership for @agardnerit

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#159]
### GitHub Username

@agardnerit

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @thisthat 
- @thschue 
- @oleg-nenashev 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

**Comment by oleg-nenashev** [comment]
I support

**Comment by thisthat** [comment]
I support

**Comment by thisthat** [comment]
Invitation sent! Welcome aboard @agardnerIT 🙌

**Comment by jetzlstorfer** [comment]
Welcome aboard @agardnerIT ! :)
