### ISSUE TITLE
Transfer project infrastructure to the CNCF

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#161]
After ascension to the incubating status, we need to transfer the project infrastructure to CNCF. It includes domains, Github Orgs, Slack, etc, etc.

## Scope

TODO

## References

- Services for CNCF projects: https://www.cncf.io/services-for-projects/#introduction

**Comment by thisthat** [comment]
I think we can close this issue by now - the CNCF owns the Keptn orgs and its resources
