### ISSUE TITLE
REQUEST: New membership for <DavidPHirsch>

### ISSUE THREAD

**Issue by DavidPHirsch** [keptn/community#162]
### GitHub Username

@DavidPHirsch

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

member 

### Requirements (for member)

- [ ] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [ ] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [ ] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [ ] I am actively contributing to 1 or more Keptn subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [ ] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @oleg-nenashev 
- @thisthat  
- @thschue

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
   community support such as slack management and community day organization 
- Issues responded to
- SIG projects I am involved with

**Comment by thisthat** [comment]
I support

**Comment by thschue** [comment]
I support

**Comment by oleg-nenashev** [comment]
I would prefer to see a non empty list of contributions before merging. Just for the reference purposes

**Comment by DavidPHirsch** [comment]
@thisthat and @thschue can we move forward here

**Comment by thisthat** [comment]
Hey @oleg-nenashev, @DavidPHirsch is quite active in supporting us with community related things such as slack management and community day organization. 
I think it is enough contribution for the `member` level

**Comment by thschue** [comment]
> I would prefer to see a non empty list of contributions before merging. Just for the reference purposes

Given the fact that he is doing lots of management and community-related work around keptn, the contribution "community support such as slack management and community day organization" which he stated in the request, seems totally valid to me.

**Comment by oleg-nenashev** [comment]
I support
