### ISSUE TITLE
REQUEST: Membership Member for @mehabhalodiya

### ISSUE THREAD

**Issue by mehabhalodiya** [keptn/community#164]
### GitHub Username

e.g. @mehabhalodiya 

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

member

### Requirements (for member)

- [X] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [X] I am actively contributing to 1 or more Keptn subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [X] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @thschue 
- @oleg-nenashev 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by mehabhalodiya** [comment]
I have created the PR https://github.com/keptn/keptn/pull/8763

**Comment by thschue** [comment]
I support, thanks for your contributions and your helpfulness in the help channel!

**Comment by oleg-nenashev** [comment]
I support
