### ISSUE TITLE
Adopt Peribolos for the permissions management

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#174]
Peribolos allows the org settings, teams and memberships to be declared in a yaml file. GitHub is then updated to match the declared configuration. It would be great to adopt it for centralized management of all Keptn orgs. Kudos to @aepfli for the tip!

See the [kubernetes/org](https://github.com/kubernetes/org) repo, in particular the [merge](https://github.com/kubernetes/org/tree/master/cmd/merge) and [update.sh](https://github.com/kubernetes/org/blob/master/admin/update.sh) parts of that repo for this tool in action.

https://github.com/kubernetes/org/tree/main/config/kubernetes

https://github.com/keptn/community/issues/174#tasklist-block-dab4118f-f720-46a9-9db9-1b2c7110c5dd

**Comment by aepfli** [comment]
For completeness, there is also peribolos as a service https://github.com/operate-first/peribolos-as-a-service - but we decided against it due to security concerns. This application has a lot of privileges :)

**Comment by oleg-nenashev** [comment]
> For completeness, there is also peribolos as a service https://github.com/operate-first/peribolos-as-a-service - but we decided against it due to security concerns. This application has a lot of privileges :)

I guess GitHub Action is the best. Services and GitHub Apps tend to go EoL

**Comment by thschue** [comment]
superseded by #220
