### ISSUE TITLE
REQUEST: Membership maintainer for @bradmccoydev

### ISSUE THREAD

**Issue by bradmccoydev** [keptn/community#175]
### GitHub Username

@bradmccoydev

### Membership level

maintainer

### Requirements (for maintainer, if applicable)

- [x] I have deep understanding of the technical goals and direction of the subproject
- [x] I have deep understanding of the technical domain (specifically the language) of the subproject
- [x] I did sustained contributions to design and direction by doing all of:
  - [x] I am authoring and reviewing proposals
  - [x] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [x] I am identifying subtle or complex issues in designs and implementation PRs
- [x] I am directly contributing to the subproject through implementation and / or review
- [x] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @thschue
- @thisthat
- @bacherfl
- @grabnerandi

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

**Comment by thisthat** [comment]
I support

**Comment by thschue** [comment]
I support

**Comment by thschue** [comment]
Brad was and is an essential driver of the GitOps topics and represented Keptn at many conferences and other talks. I see him as a significant enrichment for the Keptn project and support his request.

**Comment by oleg-nenashev** [comment]
I support. Thanks for all your contributions @bradmccoydev!

**Comment by grabnerandi** [comment]
I support this as well. Brad has shown numerous times that he is a full supporter + contributor to Keptn and the community

**Comment by StackScribe** [comment]
I support, too.  Brad exemplifies everything that is good about the Keptn community.

**Comment by christian-kreuzberger-dtx** [comment]
I support!
Have seen contributions from Brad in many repositories across keptn, keptn-contrib and keptn-sandbox :)

**Comment by bradmccoydev** [comment]
Thanks for the support everyone!

**Comment by oleg-nenashev** [comment]
Thanks all! I merged the PR and added Brad to the GitHub team
