### ISSUE TITLE
Move Killercoda tutorials to the Keptn GitHub org

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#178]
We would like to move the [Killercoda Keptn Tutorials](https://killercoda.com/keptn) to the main Keptn org so that we could maintain it along the LTS release under the community's governance umbrella

TODOs

- [ ] Move the repository, needs approval from @afzal442 
- [ ] Update the build and publishing pipeline
- [ ] TBD - Connect billing if needed
- [ ] Update external links to the source code

**Comment by oleg-nenashev** [comment]
Note:

![image](https://user-images.githubusercontent.com/3000480/198238062-1d902ee1-447b-4b93-baf8-c19be72a2cfe.png)

**Comment by afzal442** [comment]
Thanks all! It's great idea I reckoned it. I approved the transfer of my repository.

![image](https://user-images.githubusercontent.com/11625672/198335813-dbe263c8-a010-4b5e-bda6-b3a95d1f7590.png)

Let me know if that will work for you.

**Comment by agardnerIT** [comment]
We have a number of issues related to this. Closing this in favour of https://github.com/keptn/community/issues/226
