### ISSUE TITLE
REQUEST: Membership maintainer for DavidPHirsch

### ISSUE THREAD

**Issue by DavidPHirsch** [keptn/community#180]
### GitHub Username

DavidPHirsch

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP

maintainer

### Requirements (for maintainer, if applicable)

- [ ] I have deep understanding of the technical goals and direction of the subproject
- [ ] I have deep understanding of the technical domain (specifically the language) of the subproject
- [ ] I did sustained contributions to design and direction by doing all of:
  - [ ] I am authoring and reviewing proposals
  - [ ] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [ ] I am identifying subtle or complex issues in designs and implementation PRs
- [ ] I am directly contributing to the subproject through implementation and / or review
- [ ] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

@thschue 
@thisthat 
@AloisReitbauer 
@grabnerandi 

### List of contributions to the Keptn project

- organized the first keptn community day in July 2021
- maintaining the keptn slack workspace
- creation of content and community engagement for twitter and LinkedIn
- legal aspects around CLA and trademark transfer
- Swag purchase and logistics for keptn community day at Kubecon NA 2022

**Comment by oleg-nenashev** [comment]
I abstain. While it is generally fine to grant @DavidPHirsch admin permissions to help with the organization administration, I am not 100% sure it fits the CNCF definition of a voting maintainer. Also, at the moment the Maintainer charter is solely about technical contributions: https://github.com/keptn/community/blob/main/COMMUNITY_MEMBERSHIP.md#maintainer

**Comment by thschue** [comment]
As we already have some non-code contributing maintainers, and David is representing the Keptn Project for a while in a very engaged way, I support his request to get a Keptn Maintainer. 

If this doesn't fit into our current contributor ladder, I propose to push #84 forward but also retire inactive maintainers.

**Comment by oleg-nenashev** [comment]
To be clear, I am happy to support the request once the ladder is adjusted

> If this doesn't fit into our current contributor ladder, I propose to push https://github.com/keptn/community/issues/84 forward but also retire inactive maintainers.

Yes, this would be a good step forward. I would keep the "maintainer" term broadly, because in the modern open source a GitHub Org Administrator is as important as code maintainer for the community

> As we already have some non-code contributing maintainer

Me, for example :) I contribute documentation-as-code and some automation, but not that much with regards to production code

**Comment by oleg-nenashev** [comment]
While we are here, I also want to reorg the docs: https://github.com/keptn/keptn/discussions/9090

**Comment by AloisReitbauer** [comment]
David is doing a lot of work on Keptn in the background.  I am for allowing him to join the maintainers now. 

We should adjust the contributor ladder accordingly. I also want to avoid any gatekeeping. 

David has double the maintainer votes he needs. This should be a clear sign of the value of his contributions.

**Comment by AloisReitbauer** [comment]
+1 supporting this

**Comment by grabnerandi** [comment]
+1 from me as well

**Comment by thschue** [comment]
Welcome as a new Maintainer, @DavidPHirsch. 

The onboarding procedure is documented here https://github.com/keptn/community/issues/181.
