### ISSUE TITLE
[Maintainer Vote] Setting up a Bootstrap Governance Board

### ISSUE THREAD

**Issue by thschue** [keptn/community#183]
As stated in https://github.com/keptn/keptn/discussions/8991, there should be a Governance Board for Keptn.

**Responsibilities of a governance committee member could include**
* Driving the project roadmap and facilitating key decisions
* Own the overall charter, vision, and direction of the project
* Promote broad adoption of the overall project
* Provide guidance for the project maintainers
* Actively participate in the governance board meetings

As discussed with some of you personally, the bootstrap governance committee should consist of 3 individuals from 3 different organizations. Every member of the keptn organization will be eligible to vote for the bootstrap governance committee members. The nominations will be handled in a separate issue (#184).

Each Maintainer has a binding vote and should reply to this issue with +1 or -1.

**Comment by thschue** [comment]
+1

**Comment by thschue** [comment]
+1

**Comment by DavidPHirsch** [comment]
+1

**Comment by jetzlstorfer** [comment]
Hi @thschue could you please clarify on some of the items from the original description:

- Driving the project roadmap and facilitating key decisions: for the first part "driving the project roadmap", is this actually the responsibility of the governance board? how does the advisory board fit in here as well?
- Provide guidance for the project maintainers: does this mean project maintainers should/can not be part of the governance board?
- Actively participate in the steering committee meetings: is the current steering committee documented somewhere? how would the steering committee, the advisory board, and the governance board work together?

And one last general question at the end: the vote on this issue, is basically if we want to go ahead with having a governance board or not, right?

Thanks for your clarifications!

**Comment by AloisReitbauer** [comment]
Establishing a board is part of project maturity. This is about how we get there. In various discussions we came with the plan to have a bootstrap board that will establish the work and then later have regular voting on the board.

**Comment by thschue** [comment]
> Hi @thschue could you please clarify on some of the items from the original description:
> 
> * Driving the project roadmap and facilitating key decisions: for the first part "driving the project roadmap", is this actually the responsibility of the governance board? how does the advisory board fit in here as well?

The advisory board is not a decision making, but a decision building board (IMHO). The advisory board can give advice on the roadmap, but the governance board will be responsible for it (IMHO).
> * Provide guidance for the project maintainers: does this mean project maintainers should/can not be part of the governance board?

Following the previous discussions, GB members get maintainers.
> * Actively participate in the steering committee meetings: is the current steering committee documented somewhere? how would the steering committee, the advisory board, and the governance board work together?

 changed this in the description of this issue, was a copy/paste mistake.
> 
> And one last general question at the end: the vote on this issue, is basically if we want to go ahead with having a governance board or not, right?

This vote is about setting up a governance board, the vote itself will be a separate one
> 
> Thanks for your clarifications!

**Comment by bradmccoydev** [comment]
+1

**Comment by AloisReitbauer** [comment]
+1

**Comment by warber** [comment]
+1

**Comment by christian-kreuzberger-dtx** [comment]
+1

**Comment by RealAnna** [comment]
+1

**Comment by odubajDT** [comment]
+1

**Comment by grabnerandi** [comment]
+1

**Comment by bacherfl** [comment]
+1

**Comment by thisthat** [comment]
+1

**Comment by johannes-b** [comment]
+1

**Comment by mowies** [comment]
+1

**Comment by thschue** [comment]
Result: The majority of maintainers (13/18) have agreed to set up the bootstrap governance board. Therefore, we will proceed with the voting of the board.

**Comment by jetzlstorfer** [comment]
+1
