### ISSUE TITLE
[Nominations] Nominations for the Bootstrap Governance Board

### ISSUE THREAD

**Issue by thschue** [keptn/community#184]
Please express your interest in getting nominated for the bootstrap governance committee here. You can either self-nominate or get nominated, if one gets nominated, please accept this nomination by quoting this with "I accept."

You should be an active member of the Keptn Ecosystem and be able to bring up enough time to attend meetings and support the project. End Users are also welcome!

The Nomination period ends on November 16th, 2022, at 23:59 CET.

**Comment by DavidPHirsch** [comment]
I would be interested

**Comment by vadasambar** [comment]
I would be interested.

**Comment by AloisReitbauer** [comment]
I am interested. I might also be the one knowing the project for the longest :-)

**Comment by grabnerandi** [comment]
Interested as well

**Comment by braghettos** [comment]
I would be interested

**Comment by bradmccoydev** [comment]
I would be interested.

**Comment by AlexsJones** [comment]
I would be interested, I advise on the project and feel this might be a natural way to be more proactively involved.

**Comment by bradmccoydev** [comment]
Nominating @AnaMMedina21 as she is interested but not on here yet..

**Comment by AnaMMedina21** [comment]
I accept. Thanks for the nomination, @bradmccoydev. I am adding my information now to the list

**Comment by thschue** [comment]
The nomination period has passed, and the nominees are:

@AlexsJones 
@AloisReitbauer 
@AnaMMedina21
@bradmccoydev 
@braghettos 
@grabnerandi 
@vadasambar  

Good luck!
