### ISSUE TITLE
Social media posts

### ISSUE THREAD

**Issue by Giulia-dipietro** [keptn/community#208]
Please add below any links to information you'd like to share on the Keptn social media profiles (Twitter & Linkedin).

Don't forget to add your social media handles for tagging.

**Comment by grabnerandi** [comment]
Keptn Governance Board Committee Election: https://github.com/keptn/community/blob/main/elections/2022/governance-committee-election.md

**Comment by Giulia-dipietro** [comment]
Pre-release Keptn 0.20 
Community try it out and send feedback.

**Comment by Giulia-dipietro** [comment]
Announcement: only Wednesday morning community morning on a bi-weekly meeting.

**Comment by Giulia-dipietro** [comment]
Reminder: place your vote for the governance committee

**Comment by Giulia-dipietro** [comment]
New Governance Committee elected

**Comment by Giulia-dipietro** [comment]
Advertise Keptn release party https://community.cncf.io/events/details/cncf-keptn-community-presents-keptn-100-release-party/

**Comment by Giulia-dipietro** [comment]
Keptn 1.0.0 release

**Comment by Giulia-dipietro** [comment]
Keptn trivia quiz

**Comment by Giulia-dipietro** [comment]
Community meeting 21st

**Comment by Giulia-dipietro** [comment]
Happy holidays from Keptn

**Comment by bradmccoydev** [comment]
Underground Keptn Rap: https://twitter.com/AfzalShams1/status/1599829192149184512?s=20&t=DpJGP8UWgV6mmA7AsXHZlg

**Comment by grabnerandi** [comment]
@bradmccoydev - we may even get a video for this. Just got pinged by a community member showing me his rap video using that text. I hope I get him to publish - its epic :-)

**Comment by grabnerandi** [comment]
We will present at CNCF Meetup Linz on January 17th. Meeting should be announced later today. Thomas got initially confirmed but he has a conflict - now I am stepping in.
**Title**: Don’t deploy into the Dark! DORA Metrics: automatically, for all your K8s workloads!

**Comment by Giulia-dipietro** [comment]
Wednesday 21st 10 AM CET - reminder for Keptn community meeting

**Comment by Giulia-dipietro** [comment]
I'm closing the issue for this year. I'll schedule no more posts for 2022.
