### ISSUE TITLE
Send first e-mail to eligible voters via Helios

### ISSUE THREAD

**Issue by thschue** [keptn/community#210]

**Comment by thschue** [comment]
Send out a notification to all voters

**Comment by jetzlstorfer** [comment]
Hi @thschue 
I've not received any information via email. Can you please check in the distribution list if I'm added correctly? Thank you!

**Comment by jetzlstorfer** [comment]
I just realized my github handle in the maintainer file is wrong. Will create a PR for this.
I also checked all my mail accounts and I didn't receive any invite. However, with the link you provided I was able to vote.

**Comment by jetzlstorfer** [comment]
Here is the PR to fix my handle: https://github.com/keptn/keptn/pull/9179
