### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by Giulia-dipietro** [keptn/community#213]
Please add below any links to information you'd like to share on the Keptn social media profiles (Twitter & Linkedin).

Don't forget to add your social media handles for tagging.

**Comment by grabnerandi** [comment]
Upcoming CNCF Meetup in Boston in Feb 9 -> https://community.cncf.io/events/details/cncf-boston-presents-dont-deploy-into-the-dark/

**Comment by grabnerandi** [comment]
Keptn Lifecycle Toolkit Demo Tutorial on k3s, with ArgoCD for GitOps, OTel, Prometheus and Grafana --> https://www.youtube.com/watch?v=6J_RzpmXoCc

**Comment by Giulia-dipietro** [comment]
1.1 release https://github.com/keptn/keptn/pull/9323
bug fixes + performance improvements 
aiming for next week

**Comment by Giulia-dipietro** [comment]
0.5 keptn lifecycle toolkit release this week

**Comment by grabnerandi** [comment]
KCD Pakistan -> https://twitter.com/kcd_pakistan/status/1616101770593198080?s=20&t=o3vWQbsFV0cjzJLayHEq6g
Will be speaking about Keptn and DORA on that event on Feb 17th

**Comment by Giulia-dipietro** [comment]
Release Lifecycle Toolkit 0.5.0

**Comment by Giulia-dipietro** [comment]
https://www.meetup.com/lakeside-talks/events/290326522/ 
There will be a talk about Keptn at the Lakeside Talks- 09.02.23: 
Topic TBD, most likely introduction of the project, showcase how KLT supports GitOps deployments, and how to scale your workloads automagically with Dynatrace/Prometheus and the Keptn Generic Metric Server

**Comment by bradmccoydev** [comment]
Possibly we want to advertise that Keptn is applying for GSoC again?? cc @thschue

**Comment by Giulia-dipietro** [comment]
Keptn release 1.2.0 https://keptn.sh/docs/news/release_announcements/keptn-120/
KLT 0.6 tomorrow 
Lakeside talk picture

**Comment by Giulia-dipietro** [comment]
Reminder: talk from Andreas at Kubernetes Pakistan

**Comment by grabnerandi** [comment]
Slides from Boston CNCF Meetup -> https://www.slideshare.net/grabnerandi/dont-deploy-into-the-dark-dora-metrics-for-your-k8s-gitops-deployments

**Comment by Giulia-dipietro** [comment]
Is it observable episode on Keptn: https://www.youtube.com/watch?v=Uvg4uG8AbFg

**Comment by Giulia-dipietro** [comment]
Keptn Roadmap @thisthat 

Contribfest for Keptn https://kccnceu2023.sched.com/event/1HzdX/contribfest-keptn?iframe=no&w=100%25&sidebar=yes&bg=no 

KubeCon talks: 
https://kccnceu2023.sched.com/event/1HyWU/our-journey-through-cloud-native-as-mentee-and-mentor-brad-mccoy-basiq-meha-bhalodiya-student?iframe=no&w=100%25&sidebar=yes&bg=no
https://kccnceu2023.sched.com/event/1HyTy/navigating-the-delivery-lifecycle-with-keptn-giovanni-liva-dynatrace-ana-margarita-medina-lightstep-brad-mccoy-basiq-meha-bhalodiya-red-hat?iframe=no&w=100%25&sidebar=yes&bg=no 

Enhancement proposals: 
https://github.com/keptn/enhancement-proposals/pull/91
https://github.com/keptn/enhancement-proposals/pull/89
https://github.com/keptn/enhancement-proposals/pull/90
