### ISSUE TITLE
RFE: Add repository for collecting and sharing `KeptnTasks`

### ISSUE THREAD

**Issue by thisthat** [keptn/community#214]
### Proposal

[Keptn Lifecycle Toolkit](https://github.com/keptn/lifecycle-toolkit) allows users to define their own tasks to be executed. 
Tasks can also be fetched from a remote URL and parameterized so they can be reused. 
Community members started to share them over Slack but

- it is hard to find them
- can't be easily picked and used by other users

### References

Original idea from David B G.: https://keptn.slack.com/archives/CNRCGFU3U/p1674487839413669?thread_ts=1673903999.162079&cid=CNRCGFU3U

### Sponsors

- @thisthat 
- @grabnerandi 

### Checklist

- [x] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [x] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by agardnerIT** [comment]
I support 👍

**Comment by thisthat** [comment]
The repo will be created under keptn-contrib

**Comment by thisthat** [comment]
Repo: https://github.com/keptn-contrib/klt-tasks
