### ISSUE TITLE
Update project summary table in cncf/landscape for the Keptn Project

### ISSUE THREAD

**Issue by bradmccoydev** [keptn/community#215]
@CathPag has requested we update the project summary table in the cncf landscape details to raise the PR are here: https://github.com/cncf/landscape/blob/master/readme_summary.md

![image](https://user-images.githubusercontent.com/25817813/214977519-9d71f184-eb69-409f-826d-3a6b52cac298.png)

**Comment by thisthat** [comment]
Thanks @bradmccoydev, I'll take care of that

**Comment by thisthat** [comment]
PR has been merged: https://github.com/cncf/landscape/pull/3009#event-8388634276
