### ISSUE TITLE
Keptn in Google Summer of Code 2023

### ISSUE THREAD

**Issue by bradmccoydev** [keptn/community#216]
It would be nice to have Keptn participating in [Google Summer of Code 2023](https://summerofcode.withgoogle.com/) so that we could have a few students working on new Keptn integrations or some core features that do not stand on the critical path of the Keptn roadmap. It is good for community bonding, and hopefully for new contributor onboarding too.

Project applications will start in mid-January

## Potential project ideas

This list is based on the discussions with Keptn users and contributors. Please feel free to propose your ideas in the comments!

* Create additional metrics operators for KLT
  * See [keptn/integrations#19 ](https://github.com/keptn/lifecycle-toolkit/issues/745)
  * Potential mentor(s): Thomas Schue @thschue 
* Keptn Plugin for [Backstage](https://backstage.io/)
  * See keptn/integrations#19 
  * Potential mentor(s): Brad McCoy @bradmccoydev 
* Revamp the content and aesthetics of keptn.sh
  * See https://github.com/keptn/lifecycle-toolkit/issues/743
  * Potential mentor(s): Meg McRoberts @StackScribe
* Create common Git Cheatsheet document for all keptn repos
  * See https://github.com/keptn/community/issues/217
  * Potential mentor(s): Meg McRoberts @StackScribe
* Create reusable KeptnTasks and catalog
  * See @agardnerIT <Please add issue here>
  * Potential mentor(s): Adam Gardner @agardnerIT
* Document Keptn Lifecycle Toolkit
  * See @StackScribe <Please add issue here>
  * Potential mentor(s): Meg McRoberts @StackScribe

* // Add your ideas in the comments!

## References

* https://summerofcode.withgoogle.com/

**Comment by agardnerIT** [comment]
✋If we can come up with a feasible list of standardised / reusable [KeptnTasks](https://lifecycle.keptn.sh/docs/tasks/write-tasks/) that need to be implemented, happy to mentor the creation of the "catalogue"

✋I would be happy to mentor a docs project related to Keptn Lifecycle Toolkit. [Question: Can we have multiple mentors on a project: @StackScribe co-mentor?]

**Comment by StackScribe** [comment]
Yes, I believe we can have multiple mentors on a project and this is actually preferred.

**Comment by StackScribe** [comment]
Project idea: Revamp the content and the aesthetics of the keptn.sh landing page.
* Much of the content has been unchanged for a while and needs to be updated to better reflect current projects, themes, and resources.
* The look-and-feel of the page should be modernized.
* Improve navigation throughout the site.
* Implement CLA to replace DCO and make it easier to contribute to the project.
* Point to "Resources" that are current and implement a scheme that makes it easier to update those listings
* Consider a "banner" or some similar scheme that makes it easier to post current news and information, such as upcoming conferences, hackathons, et cetera

**Comment by sudiptob2** [comment]
@StackScribe @bradmccoydev 
I am an open-source beginner and this year I am looking forward to contributing to the Keptn project and be a part of the wonderful keptn community. 
Would it be possible for keptn mentors to create a **30 day learning plan** for learning the product and getting started?

I think previous **GSoC** participants can help more in this context.

For example, I am creating one myself. I am looking forward to your comments to complete the plan 

### Learning Keptn 30-day from scratch

- [ ]  **Understand the basics of Kubernetes**
    - [ ]  [Kubernetes For Beginner](https://youtu.be/X48VuDVv0do)
- [ ]  **Kubernetes Architechutre**
    - [ ]  [Philosophy](https://youtu.be/ZuIQurh_kDk)
    - [ ]  [Kubernetes Deconstructed: Understanding Kubernetes by Breaking It Down](https://www.youtube.com/watch?v=90kZRyPcRZw)
- [ ] **CRD**

  - [ ]  [Custom Resouce Definition (CRD)](https://www.youtube.com/watch?v=xGafiZEX0YA)
  - [ ]  [Kubernetes Operator simply explained in 10 mins](https://www.youtube.com/watch?v=ha3LjlD6g7g)
  - [ ]  [Writing Kubernetes Controllers for CRDs](https://www.youtube.com/watch?v=7wdUa4Ulwxg)

- [ ] **Complete at least 1 tutorial**
  - [ ] [https://book.kubebuilder.io/introduction.html](https://book.kubebuilder.io/introduction.html)

**Comment by Amishakumari544** [comment]
I agree with @sudiptob2 this is the correct way to learn more about the project also

**Comment by itisaby** [comment]
I would love to work on the Backstage Integration for Keptn. I have worked with Backstage before, where I implemented TechDocs for the Components and created a CI/CD using GitHub Actions to store them in s3. It will be a great opportunity for me as a Mentee for GSOC 2023 to work on the Backstage Plugin for Keptn. Excited for this ✨ @bradmccoydev

**Comment by harshalmittal4** [comment]
Hello, I am an open-source enthusiast and wish to participate in GSoC to develop my skills. I liked the 2022 GSoC idea to integrate k6 to Keptn, and would love to contribute to a Keptn project this year as I find Keptn interesting! Currently developing more knowledge about the project. 
Thanks!

**Comment by StackScribe** [comment]
Project proposal: Create common "git cheatsheet" document for all Keptn projects/repos (https://github.com/keptn/community/issues/217 )

**Comment by StackScribe** [comment]
Project proposal from @thschue : Create additional metrics operators for KLT (https://github.com/keptn/lifecycle-toolkit/issues/745 )

**Comment by Amishakumari544** [comment]
I am interested to work on this #743 @StackScribe

**Comment by rakshitgondwal** [comment]
Please let me know what tech stacks we use for the keptn.sh landing page? @StackScribe

**Comment by SuperAayush** [comment]
Hey @bradmccoydev!!
Keptn Plugin for Backstage is taking my whole attention here and I would love to contribute to make a reliable plugin.

My abstract idea:
[Backstage](https://backstage.io/) project has used speed paradox as a mode of achievement while using backstage where they have also mentioned "the faster you grow, the more fragmented and complex your software ecosystem becomes. And then everything slows down again." The slowing down of the process mainly occurs because it is very hard to run tests specifically manual tests on complex code structures and hence it is even harder to debug the overall process.

This is where keptn powers can be used as mentioned in this doc: https://keptn.sh/docs/concepts/performance_validation/

We can work on creating a plugin that not only helps the process to be autonomous and fast but also more robust and secure by continuous automated testing and providing vital information using dashboards. Further improvements can be done by paying focus on the testing phase where continuous deployments can be a good area to work on referring to this doc: https://keptn.sh/docs/concepts/delivery/

I hope this is a sensible one to work on 😅!!
Looking forward to getting more involved with the project and the community.

**Comment by Vrukshali-26** [comment]
@bradmccoydev 
I want to work on Keptn Plugin for Backstage. (https://github.com/keptn/integrations/issues/19)
This is something very new to me and I always wanted to know how new plugins are added to a project, and here it is. 
I am looking forward to contributing and getting involved in the community.

**Comment by rakshitgondwal** [comment]
Hey @bradmccoydev!
I am getting massive interest in two of the ideas over here.
- Better GitHub Integration in Keptn. (It would be beneficial if you or @StackScribe could open a ticket related to this and provide basic information regarding this project.)
- Create additional metrics operators for KLT- I have been exploring KLT for a while now and this is an exciting idea. I would like @thschue to help me with this and we can discuss this [over here](https://keptn.slack.com/archives/CNRCGFU3U/p1675447644590569)

I will go through both of these ideas and decide which one to work on.

**Comment by bhavyastar** [comment]
Hey @bradmccoydev!
The idea of adding a Keptn Plugin for Backstage interests me a lot. Creating a plugin for Backstage is itself a good idea as backstage is an open platform for building developer portals. 

I would really like to work on this!!
Looking forward to contributing and getting involved in the community.

**Comment by bradmccoydev** [comment]
Thanks, everyone for the ideas, and interest as both a mentor and mentee. I will now update this in the git repo and we can add the detail there regarding the project ideas as GSoC will look there when assessing our Org Application cc @StackScribe

**Comment by sudiptob2** [comment]
I have been looking at the idea of [Improve GitHub Integration in Keptn](https://github.com/keptn/community/blob/main/mentorship/gsoc/2022/project-ideas.md#improve-github-integration-in-keptn) As far as I saw this idea has not been implemented in the previous year. 

### Potential use-cases

- [ ] **GitHub App Authentication Service**
- [ ] **Support for triggering GitHub Actions from Keptn** 
- [ ] **Reporting application statuses to Deployments API.** 
- [ ] **Reporting Service Level Objectives(SLOs) and quality gate evaluation results to Checks API.**

I have experience in **Javascript**, **Golang**, and **Github Action**. I have created a **GitHub Action** based [stat generator project](https://github.com/sudiptob2/cf-stats) which has been popular among the open-source community. 

I have been learning ancillary technologies which include **Keptn** and **KTL**, **CRD**, **SLOs**, etc for the past couple of weeks. With the support of the fantastic **Keptn** community, 3 of my PRs have been merged and working on other issues regularly. It is not much but I am willing to take this learning further by participating in **GSoC.** @oleg-nenashev @bradmccoydev  had been mentoring the issue in the previous year :rocket: I am looking froward to your help and support if you think this is still a project that can be added in the **GSoC 2023.** :star2:

**Comment by agardnerIT** [comment]
Please try to join the community meeting TODAY where we will discuss GSoC at length: https://docs.google.com/document/d/1y7a6uaN8fwFJ7IRnvtxSfgz-OGFq6u7bKN6F7NDxKPg

**Comment by bradmccoydev** [comment]
We are also applying under the CNCF Mentoring page. People can make PR's like this one: https://github.com/cncf/mentoring/pull/832

**Comment by aepfli** [comment]
:raising_hand: I have a proposal regarding tooling for documentation, enforcing a particular code style, ensuring proper writing of specific names like Keptn with capitalization, and ensuring no use of insensitive words. It would cover researching what we can do, how we can do it, and applying it, running locally and within CI to ensure good quality within our documentation. (I can even offer to mentor)

**Comment by prakrit55** [comment]
Hello @bradmccoydev ,
the projects are really captivating ,I hve got an immense interest to get into the projects and be a part of this amazing community.

**Comment by thschue** [comment]
Added some project proposals here: https://github.com/cncf/mentoring/pull/836

**Comment by thschue** [comment]
In my issue, it got mentioned that documentation-only tasks can not be part of GSoC:

![image](https://user-images.githubusercontent.com/38893055/219388331-df350a35-317c-49fb-9123-0b6fd7b25c41.png)

I think this referred to the contents of this issue, e.g. https://github.com/keptn/lifecycle-toolkit/issues/743 or "Document Keptn Lifecycle Toolkit"

**Comment by aepfli** [comment]
> raising_hand I have a proposal regarding tooling for documentation, enforcing a particular code style, ensuring proper writing of specific names like Keptn with capitalization, and ensuring no use of insensitive words. It would cover researching what we can do, how we can do it, and applying it, running locally and within CI to ensure good quality within our documentation. (I can even offer to mentor)

created https://github.com/keptn/lifecycle-toolkit/issues/875

**Comment by DavidPHirsch** [comment]
@bradmccoydev  can we close this issue?
