### ISSUE TITLE
Create a common file about working with git

### ISSUE THREAD

**Issue by StackScribe** [keptn/community#217]
### Proposal

We need a single document that summarizes how to work with git and DCO for all Keptn projects.  For new users, figuring out the right thing from all the git documentation can be overwhelming so we need a simple "cheatsheat" that discusses the basic steps people need to take to create a PR.  We currently have information for this in the CONTRIBUTING.md files for individual repos but this should be consolidated into a single file that is appropriate for all projects and repositories.

* Create a page in the Contributor/Developer Guide (see https://github.com/keptn/lifecycle-toolkit/issues/212 ) that provides comprehensive information appropriate for all Keptn contributions.
* Add a link to this file from all Keptn CONTRIBUTING.md files
* Delete straight git information from other CONTRIBUTINZG.md files

This is not big enough to be a full GSoC project but it might be combined with other work or might be a good-first-issue for people preparing to be mentees.

### References

CONTRIBUTING.md files in keptin.github.io, keptn/keptn, lifecycle-toolkit, and lifecycle-toolkit/docs

### Sponsors

- (at)Meg McRoberts
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by rakshitgondwal** [comment]
I would like to take this up! @StackScribe

**Comment by rakshitgondwal** [comment]
I have made a list of things that should be mentioned in this document-

- Forking and Cloning into the local.
- Committing changes.
- Signing off commits.
- Making a PR.


@StackScribe Are there any other things that need to be mentioned in this document?
