### ISSUE TITLE
RFE: Use contrib.rocks (or other tool) to better recognise contributors

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#221]
### Proposal

All repos in Keptn could improve the way we thank contributors. One option (although I'm open to other solutions) is `https://contrib.rocks`.

It reads a repo and generates a great graphic to show contributors.

For example, here's the current one for `keptn/keptn`.

![image](https://user-images.githubusercontent.com/26523841/217490820-5a516574-4f8d-4d3a-a414-629ff6344ce4.png)

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thisthat** [comment]
I also support this idea!

**Comment by aepfli** [comment]
I saw that @agardnerIT already added `contrib.rocks` to some repositories. What else do you think we should do? How can I help to resolve this issue :)
