### ISSUE TITLE
Request to create new repository

### ISSUE THREAD

**Issue by mowies** [keptn/community#222]
For the helm chart for keptn lifecycle toolkit we need a new repository where the chart will be hosted.
The repo should be under the keptn org and it should be called `lifecycle-toolkit-charts`.

**Comment by thisthat** [comment]
Hey @mowies, I guess our bot account will mainly use this repo. Which permissions should be given to @keptn-bot?

**Comment by mowies** [comment]
the keptn-bot should have write access, and it would be great if i can get admin access :)

**Comment by thisthat** [comment]
Repository created and the permissions set: https://github.com/keptn/lifecycle-toolkit-charts
