### ISSUE TITLE
RFE: Auto close stale issues and PRs

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#224]
### Proposal

We have LOTS of very old, very stale issues and PRs in our many repos. Can we use some sort of ruleset or "stale bot" to auto close based on some criteria (to be defined)?

### Sponsors

- @thschue 
- @mowies 

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by Amishakumari544** [comment]
can we create a `yml` file for this to add stale issues after a specific either day or date?

**Comment by mowies** [comment]
@agardnerIT are you requesting this for keptn/keptn or keptn/lifecycle-toolkit?
because in keptn/keptn, we have the stalebot running already :)

in any case, i'm all for it :)

**Comment by mowies** [comment]
the probot/stale github app that we are using in keptn/keptn actually supports organization-wide configuration through the keptn/.github repo. I would suggest to move the config from keptn/keptn to keptn/.github and then extend it in every repo.

Reference: https://github.com/probot/stale/issues/220

**Comment by agardnerIT** [comment]
Not too sure this works in `keptn/keptn`. [Here's an open issue](https://github.com/keptn/keptn/issues/147) from 2019 :)

**Comment by mowies** [comment]
The `future` label is specifically exempted from the stale config :)
https://github.com/keptn/keptn/blob/master/.github/stale.yml#L9

**Comment by DavidPHirsch** [comment]
@mowies can we close this?

**Comment by mowies** [comment]
This is something that could be done as a good first issue.
Adding the stale config to the keptn/.github repo so that old issues get closed org wide.

**Comment by mowies** [comment]
nevermind, closing this
