### ISSUE TITLE
RFE: Create repository for Killercoda

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#226]
### Proposal

As discussed in the community meeting on 08/02/23, the Keptn killercoda tutorial still lives under @afzal442's personal GitHub account. We need to migrate this to an "official" Keptn repo.

Killercoda requires a dedicated repository for tutorials. Please create one and follow the [Killercoda creator docs](https://killercoda.com/creators) for how to set up the auto-sync webhook.

When done, please copy the folder from [here](https://github.com/afzal442/keptn-pg-killerway/tree/master/keptn-end-to-end-delivery) and Killercoda will autosync.

Note: Afzal has already "reserved" the `keptn` username so I may need to speak to the Killercoda admins to swap that over. Let me know and @afzal442 and I can handle it.

I want to take this opportunity to thank @afzal442  and @StackScribe for all the hard work that went (and continues to go) into this tutorial. It has undoubtedly helped many new users get up and running with Keptn more easily - thank you 🥇 

### Sponsors

- @mowies 
- @thisthat 

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by mowies** [comment]
Good idea! I sponsor this!

**Comment by thisthat** [comment]
I support this 👍

**Comment by odubajDT** [comment]
I support this

**Comment by agardnerIT** [comment]
Excellent! Can someone please set up the empty repo and configure the webhook. When done, @afzal442 and I can figure out the transfer. Thanks all!

**Comment by StackScribe** [comment]
@agardnerIT deserves major thanks for making this happen and continuing to drive the effort.

**Comment by StackScribe** [comment]
I support this.

**Comment by StackScribe** [comment]
Question: We hope to have additional Killercoda exercises in the future.  We are looking for someone to do a first-look exercise for KLT and would eventually like to have more exercises for some advanced topics.  Do we want to have one Keptn repo per Killercoda exercise or do we want one repo that stores all Killercoda exercises?  Or maybe a repo for Keptn V1 exercises and one for KLT exercises?  I think this needs to be decided before we set up the repo.

**Comment by mowies** [comment]
@thisthat could you please create the repo with @agardnerIT and @afzal442 as maintainers ? :)

**Comment by agardnerIT** [comment]
Killercoda allocates one name to one repo. Ergo if we want everything under `https://killercoda.com/keptn` that is one repo and one only repo for all tutorials. Tutorials are organised inside that repo by folders.

This setup does mean that future maintainers get “all or nothing” permissions for everything on killercoda though….

also, unless it has changed, I don’t think this works with organisation GitHub accounts so that may trip us up…

**Comment by mowies** [comment]
Then I would probably go with a repo per tutorial for now and re-evaluate when we run into scaling issues with too many tutorials.

**Comment by agardnerIT** [comment]
Remember that `/Keptn` is on the killercoda homepage. We are unlikely to get two spots. I advise a single repo containing the v1 tutorial and the klt tutorial. That way, a visitor to `https://killercoda.com/Keptn` has exposure to both versions.

**Comment by mowies** [comment]
Also sounds good :)

**Comment by thisthat** [comment]
I will wait for peribolos to create the repository. This way this can be our test-bed to test the new tool ;)

**Comment by agardnerIT** [comment]
Now that we have Peribolos. We need:

1 new repo which will hold BOTH keptn v1 and KLT tutorials

Inside this repo we will create two folders (must be named exactly this as this forms part of the kilelrcoda.com URL):

- `keptn-end-to-end-delivery`
- `klt-demo`

If folder-based permissions with repos are possible:

- @agardnerit: Permission to review, approve and merge PRs in both folders
- @afzal442: Permission to review, approve and merge PRs in `keptn-end-to-end-delivery`
- @superaayush: Permission to review, approve and merge PRs in `klt-demo`

We also need (it may exist already) some documentation on how new users can request additional permissions via Peribolos for future maintainers.

**Comment by aepfli** [comment]
@agardnerIT i created the basic configuration for the pullrequest within #269 - what will be the content and CODEOWNER configuration within that repository is something separate, we can handle afterwards.
