### ISSUE TITLE
RFE: Remove DCO

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#227]
### Proposal

This proposal is to remove DCO.

Rationale: Every commit must be signed with either the `-s` flag. e.g. `git commit -sm "my message"`

OR the following needs to be added to each commit message:

```
Signed-off-by: Humpty Dumpty <humpty.dumpty@example.com>
```

Forgetting to do so will upset the DCO bot, block PRs and generally cause arbitrary and entirely unnecessary blockers for contributors.

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thisthat** [comment]
Hey @agardnerIT, thanks for the suggestion. I agree that it would lower the barrier for new contributors but being a CNCF project, this is a requirement. https://github.com/cncf/foundation/blob/main/dco-guidelines.md
Furthermore, the DCO implementation we have provides users with the set of git commands to run for fixing problems.

**Comment by thisthat** [comment]
I will close the issue. If you have further arguments, feel free to re-open the ticket.
