### ISSUE TITLE
REQUEST: Membership maintainer for AnaMMedina21!

### ISSUE THREAD

**Issue by AnaMMedina21** [keptn/community#229]
### GitHub Username

@AnaMMedina21 

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

 **maintainer**

### Requirements (for maintainer, if applicable)

- [x] I have deep understanding of the technical goals and direction of the subproject
- [x] I have deep understanding of the technical domain (specifically the language) of the subproject
- [x] I did sustained contributions to design and direction by doing all of:
  - [x] I am authoring and reviewing proposals
  - [x] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [x] I am identifying subtle or complex issues in designs and implementation PRs
- [x] I am directly contributing to the subproject through implementation and / or review
- [x] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @thschue
- @AloisReitbauer

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- Keptn Advisory Board
- Various Keptn Talks / Video Content

**Comment by AloisReitbauer** [comment]
Supporting

**Comment by thschue** [comment]
I support

**Comment by thisthat** [comment]
Invitation sent. Welcome aboard @AnaMMedina21 🚢
