### ISSUE TITLE
RFE: Add 2023 Google doc to this repo

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#231]
[This document](https://docs.google.com/document/d/1y7a6uaN8fwFJ7IRnvtxSfgz-OGFq6u7bKN6F7NDxKPg/edit) (which tracks) all community calls is extremely hard to find.

We should add it to prominently to two places:

1) The readme of this repo (`keptn/community`) and `keptn.sh/community`

**Comment by DavidPHirsch** [comment]
this is in the community repo readme
