### ISSUE TITLE
RFE: Retirement of maintainer/approver status

### ISSUE THREAD

**Issue by mowies** [keptn/community#234]
### Proposal

I want to propose an update to the community membership policies that we have in place right now. Specifically, I want to introduce a clause to remove maintainer and/or approver status from users.
I want to give maintainers the option to retire by themselves and become some form of emeritus where they and their contributions are still honored even after their status is removed.
Additionally, I want to kind of have a "timeout". After a certain amount of time (e.g. 6 or 12 months) the maintainer/approver status can be removed from members by other maintainers if they didn't perform their duties as maintainers/approvers in that timeframe.

It should also be easier for "emeritus" members to come back to active duty when they want to. This should be enabled by having other maintainers "sponsor" their comeback without necessarily going through the whole membership chain again.

In any case, the organization member status should not be removed by deprecation over time.

I put two links so similar policies from etcd [1] and OTel [2] into the references.

### References
[1] https://github.com/etcd-io/etcd/blob/main/GOVERNANCE.md#nomination-and-retiring-of-maintainers
[2] https://github.com/open-telemetry/community/blob/main/community-membership.md#emeritus-maintainerapprovertriager

### Sponsors

- @thschue 
- @heckelmann 
- @thisthat 

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by heckelmann** [comment]
I support

**Comment by thschue** [comment]
I support

**Comment by thisthat** [comment]
I also support this. Thanks for the proposal @mowies 🙌

**Comment by bacherfl** [comment]
I support

**Comment by StackScribe** [comment]
I support.  I especially like the fact that emeriti names will not be erased.

**Comment by DavidPHirsch** [comment]
looks like a great idea! I would also get approval for the governance committee

**Comment by bradmccoydev** [comment]
I support

**Comment by AloisReitbauer** [comment]
We will discuss this in the GC together with @AlexsJones and @AnaMMedina21. I think we overall need a mechanism like this. 

I would just like to have a very explicit way how people move to emeritus from active maintainer if - for example - they just no longer show up to meetings etc.  My proposal is that the active maintainers first reach out to the non-active member. If they do not engage and do not contribute for more than e.g 6 months the GC can decide to move them to emeritus.

**Comment by DavidPHirsch** [comment]
To add I would try to define some requirements:
APPROVERS
in the last 4 months
- no code reviews/approvals
- no active participation in community meetings

MAINTAINERS
in the last 4 months
- approver criteria plus
- has not authored/reviewed any KEPs
- has not directly contributed to the subproject through implementation and / or review


Required actions to change to emeritus:

- [ ] contact person by email/slack or tag in issue
- [ ] a maintainer should open a PR with the details of the person to be moved to emeritus
- [ ] TC/GC should be put as reviewers

Any other ideas?or any comments?

**Comment by heckelmann** [comment]
> To add I would try to define some requirements: APPROVERS in the last 4 months
> 
> * no code reviews/approvals
> * no active participation in community meetings
> 
> MAINTAINERS in the last 4 months
> 
> * approver criteria plus
> * has not authored/reviewed any KEPs
> * has not directly contributed to the subproject through implementation and / or review
> 
> Required actions to change to emeritus:
> 
> * [ ]  contact person by email/slack or tag in issue
> * [ ]  a maintainer should open a PR with the details of the person to be moved to emeritus
> * [ ]  TC/GC should be put as reviewers
> 
> Any other ideas?or any comments?

Is it 
* no code reviews/approvals **_[AND / OR]_**
* no active participation in community meetings

**Comment by mowies** [comment]
IMHO it's enough if maintainers review the membership change. I don't think it's necessary to involve the TC/GC for that.

**Comment by DavidPHirsch** [comment]
@mowies maybe we can close this for now, the last discussion was 10 month ago
