### ISSUE TITLE
REQUEST: Membership Member for @afzal442

### ISSUE THREAD

**Issue by afzal442** [keptn/community#236]
### GitHub Username

@afzal442 

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

### Requirements (for maintainer, if applicable)

- [x] I have deep understanding of the technical goals and direction of the subproject
- [x] I have deep understanding of the technical domain (specifically the language) of the subproject
- [x] I did sustained contributions to design and direction by doing all of:
  - [ ] I am authoring and reviewing proposals
  - [ ] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [x] I am identifying subtle or complex issues in designs and implementation PRs
- [x] I am directly contributing to the subproject through implementation and / or review
- [x] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors
@thschue 
@agardnerIT 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- maintained the keptn killercoda tutorial repo
- support cloud native projects tools content and community engagement on [twitter](https://twitter.com/mydevopsseries)

**Comment by thisthat** [comment]
Hey @afzal442 thanks for the request. I don't think you should be running for the maintainer status given your contributions.
I suggest requesting the member level and granting you the maintainer level in the killercoda repository. WDYT?
Please, speak also with some maintainers of the project in Slack

**Comment by afzal442** [comment]
Thanks @thisthat! I updated my info on the box requesting for `member` level. LMK if that sounds good.

**Comment by thschue** [comment]
As @afzal442 made valuable contributions to the project (especially the killercoda tutorials), I support his request to get a member.

**Comment by agardnerIT** [comment]
I support his request for membership 👍

**Comment by thisthat** [comment]
I see @afzal442 as a member is the list. I will close this issue

**Comment by thisthat** [comment]
> I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS?rgh-link-date=2023-02-20T17%3A40%3A10Z) and referenced this issue in the PR

@afzal442 could you please provide a PR to add your username to the Maintainer file? :)

**Comment by afzal442** [comment]
Sure! Thanks I will do that.
