### ISSUE TITLE
REQUEST: Technical Committee Membership for @thisthat

### ISSUE THREAD

**Issue by AloisReitbauer** [keptn/community#237]
### GitHub Username

@thisthat

### Membership level

Technical Committee member

### Sponsors

- @AloisReitbauer 

### List of contributions to the Keptn project

- Giovanni has been driving many releases of the Keptn project including the 1.0 LTS release.
- He was instrumental in delivering the Keptn lifecycle toolkit. 
- He is a strong member and mentor in the community on a wide range of topics. 
- Giovanni is the longest active members with the deepest understanding of the Keptn codebase and has extensive experience on running Keptn in large production environments.

**Comment by StackScribe** [comment]
I SUPPORT!!!!!!!!

**Comment by bradmccoydev** [comment]
I support. He has shown great leadership

**Comment by AnaMMedina21** [comment]
I support!

**Comment by thschue** [comment]
Giovanni showed excellent technical leadership skills for the project, and I think making him a TC member is more than deserved. Therefore, I totally support this request.

**Comment by AlexsJones** [comment]
I support
