### ISSUE TITLE
Make repository content renderable with HUGO

### ISSUE THREAD

**Issue by aepfli** [keptn/community#244]
### Proposal

This repository contains a lot of great information regarding our community.
Sadly it is hard to navigate, and also, it is hard to get an overview of our community from all kinds of documentation pages.
Finding this repo is hard, and navigating it is way worse.

Adapting this repository to make the Markdown files renderable with Hugo allows us to include them within each documentation set.
Instead of maintaining a community section per Website, we can include those files within each and have one source of truth

see https://deploy-preview-10--cool-wisp-bbb60d.netlify.app/, which includes the files in the community section base (those with titles etc., have been adopted in my fork)

## Optional step

We could also setup netlify within this branch for verification of the documentation

**Comment by DavidPHirsch** [comment]
@aepfli can we close this?
