### ISSUE TITLE
RFE: Official status for artifact hub repos

### ISSUE THREAD

**Issue by mowies** [keptn/community#245]
### Proposal

Artifact hub is used to host our helm charts both for [KLT](https://artifacthub.io/packages/helm/lifecycle-toolkit/klt) and [Keptn LTS](https://artifacthub.io/packages/helm/keptn/keptn). They support so-called "official" badges for repos if the owner of the helm chart is also the owner of the software that the helm chart installs.
We could apply for that official status to have the badge show up next to the repos there.
Application is done through a github issue [here](https://github.com/artifacthub/hub/issues/new/choose) and should be quite straight forward (see [OFO ticket](https://github.com/artifacthub/hub/issues/2848) that was done in a few hours).

### References
https://artifacthub.io/docs/topics/repositories/#official-status

### Sponsors

- @thisthat 
- (at)sponsor-2

### Checklist

- [x] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [x] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thisthat** [comment]
👍 I support!

**Comment by thschue** [comment]
🚀 I support!

**Comment by mowies** [comment]
Thanks for the support! I will go ahead and create the status change request in the artifact hub github repo.

**Comment by mowies** [comment]
We received the official badge for both repos, closing this.
