### ISSUE TITLE
RFE: Allow standard users to tag their issues or request a tag

### ISSUE THREAD

**Issue by agardnerIT** [keptn/community#255]
### Proposal

Standard users (non-Keptn maintainers) can create issues throughout the Keptn org). But they remain untagged.

Is it possible to allow users to tag (or request a tag) on their own issues? This would reduce the overhead on the limited number of Keptn core team to review and tag all posts.

For example, if I raise something that I believe is a good first issue, can I request that tag. Perhaps it is automatically added (since it is my issue) OR it is held in a review queue.

This delegation would make things easier and encourage community involvement as issues would be more organised and Keptn would like have far more well categorised issues and thus more community participation.

There are possibly GitHub actions that can do this and / or AI bots that can analyse the issue text content and auto-tag?

### Sponsors

- @aepfli 
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by agardnerIT** [comment]
Found a GitHub action: https://github.com/github/issue-labeler

@aepfli FYI

**Comment by aepfli** [comment]
i support this!

**Comment by DavidPHirsch** [comment]
it looks like there is no solution to allow non member to assign themselves issues, the easiest way is to have them join the org
