### ISSUE TITLE
RFE: Improve Secret Management with Password Storage Tool

### ISSUE THREAD

**Issue by aepfli** [keptn/community#256]
### Proposal

Keptn has a lot of secrets to handle - `keptn-bot`, etc. - some of those tools need two-factor authentication and other features. Sharing these secrets and a 2FA might be challenging. Therefore, eg. 1Passwords offers a nice solution, as it can also be used as a 2FA.

1Password offers free licenses to open source initiatives. We only need to create an account and apply - see https://github.com/1Password/1password-teams-open-source

### References

- [1password guide  for OSS](https://github.com/1Password/1password-teams-open-source)
- [CNCF Tools for projects](https://www.cncf.io/services-for-projects/#tools)

### Sponsors

- @mowies
- @thisthat 

### Checklist

- [x] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default) - during community meeting
- [x] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by aepfli** [comment]
@thisthat :)

**Comment by aepfli** [comment]
if this RFE is approved, i will gladly take care of account creation - i will add @thisthat and @mowies and keptnproject@gmail.com as owners and will remove myself from it afterwards :)

**Comment by mowies** [comment]
i support!

**Comment by thisthat** [comment]
I support!

**Comment by aepfli** [comment]
1Password storage created: https://keptn.1password.com/home

@keptn-bot @thisthat and @mowies are owners

**Comment by thisthat** [comment]
Added an entry in the community meeting to raise awareness for the other maintainers to share their emails with us
Thanks @aepfli, we can close this ticket now
