### ISSUE TITLE
Repositories to be archived

### ISSUE THREAD

**Issue by mowies** [keptn/community#257]
This ticket is a split off of #250 so that we can group projects that need to be archived in the various Keptn organizations.

The list of projects will be updated when people answer to #250 and want they project to be archived.

Projects to be archived:
https://github.com/keptn-contrib/servicenow-service
https://github.com/keptn-sandbox/gitlab-tutorial
https://github.com/keptn-sandbox/ansibletower-service
https://github.com/keptn-sandbox/slackbot-service
https://github.com/keptn-sandbox/jira-service
https://github.com/keptn-sandbox/keptn-osticket-service

**Comment by DavidPHirsch** [comment]
@mowies can i go ahead and archive the repos?

**Comment by mowies** [comment]
yes, please!
