### ISSUE TITLE
RFE: Allow Technical Steering Committee to approve and merge Community related Pull Requests

### ISSUE THREAD

**Issue by aepfli** [keptn/community#270]
### Proposal

With Peribolos, we now have an excellent and transparent way within this repository to manage our users.

But this increases the pull requests within this repository, primarily for permissions and assignments to teams. To move faster and onboard users and permissions faster it would be good to increase the code ownership to more people than only the governance committee. As we do have a group of "trusted" and "respected" members of this organization in the form of the Technical steering committee, I do think it makes sense to elevate the rights of the TSC and add them as CodeOwners within the community repository.

### Sponsors

- @thisthat 
- @mowies

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thisthat** [comment]
I support this change

**Comment by mowies** [comment]
I support
