### ISSUE TITLE
Bug: Community structure is not represented in peribolos configuration

### ISSUE THREAD

**Issue by thschue** [keptn/community#273]
The [community membership](https://github.com/keptn/community/blob/main/community-membership.md) document states that the membership in the maintainer team in the GitHub organization and the respective peribolos group defines the maintainer state. 

After the migration to Peribolos, there are only two more maintainers in the [maintainers](https://github.com/orgs/keptn/teams/maintainers) team. 

Therefore, this should be fixed in the contributor ladder document or in Peribolos. 

cc: @thisthat, @bradmccoydev

**Comment by thisthat** [comment]
I think that group is "artificial" and doesn't have any permission linked to any repo. Please let me know if I am wrong @aepfli. 
This is the team that represents the maintainers: https://github.com/orgs/keptn/teams/keptn-maintainers

**Comment by thschue** [comment]
In this case, we are linking to the wrong group in this document: https://github.com/keptn/community/blob/main/community-membership.md

**Comment by DavidPHirsch** [comment]
@thisthat @thschue is this still valid with the peribolos set up?

**Comment by thisthat** [comment]
@DavidPHirsch  we still need to fix the https://github.com/keptn/community/blob/main/community-membership.md file. I'll prepare a PR
