### ISSUE TITLE
REQUEST: Membership member for SuperAayush

### ISSUE THREAD

**Issue by SuperAayush** [keptn/community#274]
### GitHub Username

@SuperAayush
### Subproject

Subproject based on the folders within [Peribolos Configuration Directory][Peribolos Configuration Directory]

### Subproject Membership level

Membership level according to [Community Membership Guidelines][Community Membership Guidelines]

member 

### Requirements (for member)

- [X] I have reviewed the [Community Membership Guidelines][Community Membership Guidelines]
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [X] I am actively contributing to 1 or more Keptn subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as a community member within the [Peribolos Configuration][Peribolos Configuration] and referenced this issue in the PR

### Sponsors

- @thisthat 
- @aepfli 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs:

1. [ Killercoda new issue link redirect correction](https://github.com/afzal442/keptn-pg-killerway/pull/75)
2. [Structured and added helm prerequisite](https://github.com/keptn/keptn.github.io/pull/1609)

- Issues I have created:

1. [Killercoda new issue link redirect correction](https://github.com/keptn/keptn/issues/9502)
2. [Move the Killercoda Demo to Keptn Repo](https://github.com/keptn/keptn/issues/9501)
3. [Addition of prerequisite for helm in website docs](https://github.com/keptn/keptn.github.io/issues/1594)
4. [Enhance docs for mac users](https://github.com/keptn/keptn.github.io/issues/1595)
5. [KLT cert-manager installation type fails](https://github.com/keptn/lifecycle-toolkit/issues/1120)

- [Working on making the Killercoda demo for Keptn Lifecycle Toolkit(KLT)](https://github.com/SuperAayush/KLT-Killercoda)

[Community Membership Guidelines]: https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md
[Peribolos Configuration]: ./config/keptn/org.yaml
[Peribolos Configuration Directory]: ./config/keptn/

**Comment by thisthat** [comment]
I support

**Comment by bradmccoydev** [comment]
I Support

**Comment by aepfli** [comment]
i went ahead and generated https://github.com/keptn/community/pull/275 to grant @SuperAayush access
