### ISSUE TITLE
REQUEST: Membership Member for @staceypotter

### ISSUE THREAD

**Issue by staceypotter** [keptn/community#288]
### GitHub Username

@staceypotter 

### Subproject

Subproject based on the folders within [Peribolos Configuration Directory][Peribolos Configuration Directory]

### Subproject Membership level

Membership level according to [Community Membership Guidelines][Community Membership Guidelines]

member

### Requirements (for member)

- [x] I have reviewed the [Community Membership Guidelines][Community Membership Guidelines]
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as a community member within the [Peribolos Configuration][Peribolos Configuration] and referenced this issue in the PR

### Sponsors

- @thisthat 
- @bradmccoydev 
- @StackScribe 
- @mowies

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- https://github.com/keptn/keptn.github.io/pull/1646
- https://github.com/keptn/community/pull/287
- I also post on Slack, LinkedIn, Twitter, YouTube to reach out to the Community there about meetings, upcoming events, getting involved and promoting various content. (slack examples: https://keptn.slack.com/archives/CFH319TPE/p1685470793614199, https://keptn.slack.com/archives/CFH319TPE/p1685981008595639) 

[Community Membership Guidelines]: https://github.com/keptn/community/blob/main/community-membership.md
[Peribolos Configuration]: ./config/keptn/org.yaml
[Peribolos Configuration Directory]: ./config/keptn/

**Comment by thisthat** [comment]
I fully support 😁

**Comment by staceypotter** [comment]
The links for Peribolos seem to be broken in this issue template....

**Comment by bradmccoydev** [comment]
I support, we are very happy and lucky to have Stacey working with us on the Keptn project

**Comment by StackScribe** [comment]
I totally support!  Looking forward to all the great things that Stacey is going to contribute!

**Comment by mowies** [comment]
I support!

**Comment by staceypotter** [comment]
Created https://github.com/keptn/community/pull/289

**Comment by thschue** [comment]
I support, welcome on board 🥳
