### ISSUE TITLE
REQUEST: Membership member for @geoffrey1330

### ISSUE THREAD

**Issue by geoffrey1330** [keptn/community#293]
### GitHub Username

@geoffrey1330

### Subproject

Subproject based on the folders within [Peribolos Configuration Directory][Peribolos Configuration Directory]

### Subproject Membership level

Membership level according to [Community Membership Guidelines][Community Membership Guidelines]

member

### Requirements (for member)

- [x] I have reviewed the [Community Membership Guidelines][Community Membership Guidelines]
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as a community member within the [Peribolos Configuration][Peribolos Configuration] and referenced this issue in the PR
### Sponsors

- @odubajDT
- @RealAnna

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

#### PRs reviewed / authored
- https://github.com/keptn/lifecycle-toolkit/pull/1514
- https://github.com/keptn/lifecycle-toolkit/pull/1534
- https://github.com/keptn/lifecycle-toolkit/pull/1563
- https://github.com/keptn/lifecycle-toolkit/pull/1604

#### Issues responded to
https://github.com/keptn/lifecycle-toolkit/issues/1527
https://github.com/keptn/lifecycle-toolkit/issues/1486
https://github.com/keptn/lifecycle-toolkit/issues/1457
https://github.com/keptn/lifecycle-toolkit/issues/1445

[Community Membership Guidelines]: https://github.com/keptn/community/blob/main/community-membership.md
[Peribolos Configuration]: ./config/keptn/org.yaml
[Peribolos Configuration Directory]: ./config/keptn/

**Comment by RealAnna** [comment]
I support

**Comment by odubajDT** [comment]
I support

**Comment by bradmccoydev** [comment]
I support. Can you please make the PR

**Comment by geoffrey1330** [comment]
Created the PR #298

**Comment by thisthat** [comment]
PR merged @geoffrey1330 , please let me know when you accept the invitation so we can close this issue :) 
Please, double check on your Spam folder because sometimes it gets there 😅

**Comment by geoffrey1330** [comment]
Hi @thisthat I have accepted the Invitation.

**Comment by geoffrey1330** [comment]
> 

Thanks
