### ISSUE TITLE
REQUEST: Membership member for @YashPimple

### ISSUE THREAD

**Issue by YashPimple** [keptn/community#294]
### GitHub Username

@YashPimple
### Subproject

Subproject based on the folders within [Peribolos Configuration Directory][Peribolos Configuration Directory]

### Subproject Membership level

Membership level according to [Community Membership Guidelines][Community Membership Guidelines]

member 

### Requirements (for member)

- [X] I have reviewed the [Community Membership Guidelines][Community Membership Guidelines]
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [X] I am actively contributing to 1 or more Keptn subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as a community member within the [Peribolos Configuration][Peribolos Configuration] and referenced this issue in the PR

### Sponsors

- @StackScribe 
- @agardnerIT 

Each sponsor should reply to this issue with the comment "I support".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
   https://github.com/keptn/lifecycle-toolkit/pull/1523
   https://github.com/keptn/lifecycle-toolkit/pull/1484
   https://github.com/keptn/lifecycle-toolkit/pull/1412
   https://github.com/keptn/lifecycle-toolkit/pull/1411
   
- Issues responded to
   https://github.com/keptn/lifecycle-toolkit/issues/1609
   
[Community Membership Guidelines]: https://github.com/keptn/community/blob/main/community-membership.md
[Peribolos Configuration]: ./config/keptn/org.yaml
[Peribolos Configuration Directory]: ./config/keptn/

**Comment by agardnerIT** [comment]
I support

**Comment by StackScribe** [comment]
I support!

**Comment by thisthat** [comment]
Hey @YashPimple thanks a lot for supporting us :)
Could you please add a PR to the [community repo](https://github.com/keptn/community/) adding yourself to the Peribolos configuration? Similarly to what this PR did https://github.com/keptn/community/pull/289/files

I noticed that the template has a wrong link for that item, I will fix it ;)

**Comment by YashPimple** [comment]
Created #297

**Comment by bradmccoydev** [comment]
I Support, we have merged this PR, once you confirm that you have accepted the org we can close this issue @YashPimple

**Comment by YashPimple** [comment]
Hello @bradmccoydev I have accepted the request

**Comment by bradmccoydev** [comment]
thanks welcome aboard!
