### ISSUE TITLE
REQUEST: Membership maintainer for @agardnerIT

### ISSUE THREAD

**Issue by bradmccoydev** [keptn/community#302]
Kicking this issue off for request to add Adam as a maintainer to this project.

Adam is vital to the success of the Keptn project and has been a critical person in the migration to the new Keptn. Adding him as a maintainer would reward these efforts and make him feel empowered to continue his efforts to push this project forward.
 
### GitHub Username

@agardnerIT

### Subproject

Subproject based on the folders within [Peribolos Configuration Directory][Peribolos Configuration Directory]

### Subproject Membership level

maintainer

### Requirements (for maintainer, if applicable)

- [x] I have deep understanding of the technical goals and direction of the subproject
- [x] I have deep understanding of the technical domain (specifically the language) of the subproject
- [x] I did sustained contributions to design and direction by doing all of:
  - [x] I am authoring and reviewing proposals
  - [x] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [x] I am identifying subtle or complex issues in designs and implementation PRs
- [x] I am directly contributing to the subproject through implementation and / or review
- [x] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [ ] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as subproject maintainer within the [Peribolos Configuration Directory][Peribolos Configuration Directory] for the specific subproject and referenced this issue in the PR

### Sponsors

- @bradmccoydev 
- (at)sponsor-2

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

[Community Membership Guidelines]: https://github.com/keptn/community/blob/main/community-membership.md
[Peribolos Configuration]: ./config/keptn/org.yaml
[Peribolos Configuration Directory]: ./config/keptn/

**Comment by AnaMMedina21** [comment]
I support!
