### ISSUE TITLE
REQUEST: Membership approver for rakshitgondwal

### ISSUE THREAD

**Issue by rakshitgondwal** [keptn/community#305]
### GitHub Username

@rakshitgondwal 

### Subproject

Subproject based on the folders within [Peribolos Configuration Directory][Peribolos Configuration Directory]

[keptn/lifecycle-toolkit](https://github.com/keptn/lifecycle-toolkit)

### Subproject Membership level

Membership level according to [Community Membership Guidelines][Community Membership Guidelines]

approver

### Requirements (for approver, if applicable)

- [x] I am a reviewer of the codebase for at least 1 month
- [x] I am a reviewer for/or author of substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g., refactors/adds new functionality rather than one-line changes).
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as subproject approver within the [Peribolos Configuration Directory][Peribolos Configuration Directory] for the specific subproject and referenced this issue in the PR

### Sponsors

- @bacherfl 
- @thisthat 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored

  A total of 22 PRs merged, 2 are still open.
  https://github.com/keptn/lifecycle-toolkit/pulls/rakshitgondwal

- Issues responded to

  https://github.com/keptn/lifecycle-toolkit/issues/created_by/rakshitgondwal

[Community Membership Guidelines]: https://github.com/keptn/community/blob/main/community-membership.md
[Peribolos Configuration]: ./config/keptn/org.yaml
[Peribolos Configuration Directory]: ./config/keptn/

**Comment by bacherfl** [comment]
I support!

**Comment by thisthat** [comment]
I strongly support! @rakshitgondwal provided several high-quality PRs to enhance the metric-operator
