### ISSUE TITLE
2023 Keptn Governance Committee Elections

### ISSUE THREAD

**Issue by DavidPHirsch** [keptn/community#312]
Issue to track the 2023 elections

For information on the election process see: https://github.com/keptn/community/blob/main/elections/2023/governance-committee-election.md

If you want to nominate yourself or someone else, open a PR to https://github.com/keptn/community/blob/main/elections/2023/governance-committee-candidates.md  with the following details:

- Full name
- GitHub alias
- Company affiliation (if applicable)
- Short bio or reasoning to join the Governance Committee (no more than a short paragraph)
- Optional: photo/picture of a nominee

**Comment by DavidPHirsch** [comment]
@TannerGabriel
@TannerGilbert
@telltale00
@thelinuxfoundation
@thisthat
@thschue
@vadasambar
@warber
@YashPimple

**Comment by jetzlstorfer** [comment]
Thanks @DavidPHirsch for the heads-up and letting all members know! 
Voting works (at least on my end) 🙂
All the best for all candidates! 🍀

**Comment by AloisReitbauer** [comment]
I get the following error:  
<img width="1022" alt="image" src="https://github.com/keptn/community/assets/478193/b0331ab7-9520-4c84-b96f-12d7b6ae8926">

**Comment by Kavindu-Dodan** [comment]
@AloisReitbauer you can log in using Github sso. For this, use the login using the button at the bottom left-hand corner. Then use GitHub sso. 
![image](https://github.com/keptn/community/assets/8186721/10a52721-0063-49a4-af25-d5ebef8a937a)

**Comment by staceypotter** [comment]
Results are in from our elections! 🎉 Congratulations to @salaboy & @thschue on winning 2 of the 3 available Governance Committee seats! 🎊 

There is a tie between @AnaMMedina21 & @DavidPHirsch for the third seat, so we'll have a tie-breaker vote via [helios](https://vote.heliosvoting.org/helios/elections/66062a94-fb9e-4ca1-9475-4dd0a9e9ce85/view) from January 10, 2024 - January 24, 2024.

**Comment by DavidPHirsch** [comment]
@AnaMMedina21 I have withdrawn my candidacy. Can we announce that you will be taking the remaining seat?

**Comment by DavidPHirsch** [comment]
Congratulations to @AnaMMedina21  @salaboy @thschue on their new role in the project!
