### ISSUE TITLE
RFE: Update CNCF landscape to link to lifecycle-toolkit repo

### ISSUE THREAD

**Issue by mowies** [keptn/community#334]
### Proposal

Since Keptn v1 is now EOL, we should go ahead and update this also in the CNCF landscape so that people are guide to the correct repositories from there.

### Sponsors

- @thisthat 
- @bradmccoydev 

### Checklist

- [ ] Update landscape file [here](https://github.com/cncf/landscape/blob/master/landscape.yml)

**Comment by thisthat** [comment]
I sponsor this 👍

**Comment by bradmccoydev** [comment]
I sponsor this

**Comment by bacherfl** [comment]
I sponsor this

**Comment by mowies** [comment]
thanks for the sponsorings!
i will go ahead and implement the change then :)

**Comment by mowies** [comment]
PR against the landscape repo is open: https://github.com/cncf/landscape/pull/3706

**Comment by mowies** [comment]
done and merged ✔️
