### ISSUE TITLE
Broken link in organisation membership request issue template

### ISSUE THREAD

**Issue by sambhavgupta0705** [keptn/community#339]
When we create a new issue for membership request then there is broken link in [template ](https://github.com/keptn/community/issues/new?template=membership.md&title=REQUEST%253A%25New%2520=membership%2520for%2520%253Cyour-GH-handle%253E)
![image](https://github.com/keptn/community/assets/81870866/4a2d7ecd-a559-40cc-9ba9-69e56c9bd5e1)

**Comment by mowies** [comment]
Good catch! The  link should point to https://github.com/keptn/community/tree/main/config/keptn
