### ISSUE TITLE
RFE: Add a slack bot to our Keptn channel in the CNCF Slack

### ISSUE THREAD

**Issue by RealAnna** [keptn/community#351]
### Proposal

We would benefit from a Slack bot reminding users of the community-related meetings: 

- every other Wednesday CET  or NORAM community meeting
- the scheduled monthly user groups 
- etc.

It would be good also to have a call for questions/topics, so that users can add them to the agenda or under the Slack message.

### Sponsors

- Keptn maintainers

**Comment by mowies** [comment]
I added 2 slack workflows to the keptn cncf slack channel now that will post community meeting reminders for the 2 timeslots
