### ISSUE TITLE
Links in readme show 404 - not found on website

### ISSUE THREAD

**Issue by AryanBakliwal** [keptn/community#353]
Keptn slack, meetings and contribute display 404-not found
Link to slack page is [https://keptn.sh/community/#slack](https://keptn.sh/community/#slack)

![image](https://github.com/keptn/lifecycle-toolkit/assets/106430579/83825d01-da63-48c9-a8b1-606a1b461847)
The community page also shows the same error.

**Comment by mowies** [comment]
a PR from you would be appreciated @AryanBakliwal  :)

**Comment by AryanBakliwal** [comment]
Hi @mowies, I have opened a PR, please review. [https://github.com/keptn/.github/pull/12](https://github.com/keptn/.github/pull/12)
