### ISSUE TITLE
Publish Video: Keptn Setup & Contributions with GitHub Codespaces Tutorial

### ISSUE THREAD

**Issue by UtkarshUmre** [keptn/community#354]
**What type of content is this?**
video

[Keptn + GitHub Codespaces: Setup & Contributing Tips](https://drive.google.com/file/d/1wlkONAAWPVmjaQNI1arrfiIoViSSdNJl/view)

**On which platform should we share the content?**
YouTube

**Do you have any suggested hashtags, text, or people/companies/projects we should include?**
keptn, codespaces

**Publishing date/time**
ASAP

**Additional Notes**
kindly include these two commands in the description box for added convenience
```
1) curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

2) sudo install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
```

**Comment by DavidPHirsch** [comment]
uploaded to youtube https://studio.youtube.com/video/HdiXPgvfgQw
