### ISSUE TITLE
REQUEST: New membership for @arthurpitman

### ISSUE THREAD

**Issue by arthurpitman** [keptn/community#39]
### GitHub Username

@arthurpitman

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)

- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @johannes-b 
- @agrimmer

### List of contributions to the Keptn project

- https://github.com/keptn-contrib/dynatrace-service/pull/327
- https://github.com/keptn-contrib/dynatrace-service/pull/333
- https://github.com/keptn-contrib/dynatrace-service/pull/332
- https://github.com/keptn-contrib/dynatrace-service/issues/180
- https://github.com/keptn-contrib/dynatrace-service/issues/227
- https://github.com/keptn-contrib/dynatrace-service/issues/310

**Comment by johannes-b** [comment]
I support

**Comment by agrimmer** [comment]
I strongly support it!

**Comment by johannes-b** [comment]
Welcome, @arthurpitman! Invite sent
