### ISSUE TITLE
REQUEST: New membership for @warber @christian-kreuzberger-dtx @laneli @ermin-muratovic @bacherfl

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/community#41]
### Multi-request for Keptn core developer team

Please note, that these people are already maintainers. This issue is created for bookkeeping purposes.

* Bernd Warmuth @warber 
* Christian Kreuzberger @christian-kreuzberger-dtx
* Elisabeth Lang @laneli 
* Ermin Muratovic @ermin-muratovic 
* Florian Bacher @bacherfl

### Requirements

- [x] We have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] We have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] We have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x]  We are actively contributing to 1 or more Keptn subprojects
- [x] We have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jetzlstorfer 
- @johannes-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

The aforementioned members have been actively contributing to the Keptn project (multiple repos) for several months, some of them even more than a year. They are also listed as top contributors: https://github.com/keptn/keptn/graphs/contributors

**Comment by jetzlstorfer** [comment]
I support

**Comment by johannes-b** [comment]
I support

**Comment by christian-kreuzberger-dtx** [comment]
Thanks! Accepted.
