### ISSUE TITLE
REQUEST: New membership maintainer for @Kirdock (Klaus Strießnig)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/community#42]
### Klaus Strießnig

@Kirdock (currently approver)

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @christian-kreuzberger-dtx 
- @johannes-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

Klaus is one of the core contributors to Keptn Bridge, and has touched several parts of the product already for more than 6 months.

![image](https://user-images.githubusercontent.com/56065213/120317011-651f2400-c2de-11eb-8777-c0151d22fe12.png)

* 90+ Commits: https://github.com/keptn/keptn/commits?author=Kirdock
* 47+ merged PRs: https://github.com/keptn/keptn/pulls?q=is%3Apr+author%3AKirdock+is%3Aclosed
* 24+ Issues created: https://github.com/keptn/keptn/issues/created_by/Kirdock

**Comment by christian-kreuzberger-dtx** [comment]
I support

**Comment by johannes-b** [comment]
I support

**Comment by christian-kreuzberger-dtx** [comment]
Thanks! @johannes-b or @jetzlstorfer may I ask you to move Klaus into the maintainer group within the org?

**Comment by johannes-b** [comment]
I will do it.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks, I'm closing this issue as everything has been done!
