### ISSUE TITLE
REQUEST: Maintainer membership for @grabnerandi @AloisReitbauer @danielkhan

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/community#44]
### Multi-request for Keptn maintainer team

Please note, that these people are already maintainers. This issue is created for bookkeeping purposes.

* Andreas Grabner @grabnerandi  
* Alois Reitbauer @AloisReitbauer 
* Daniel Khan @danielkhan  

### Requirements

- [x] We have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] We have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] We have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x]  We are actively contributing to 1 or more Keptn subprojects in terms of guiding the direction of the project
- [x] We have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @christian-kreuzberger-dtx  
- @johannes-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

The aforementioned members have been actively contributing to the Keptn project for several months and are driving the direction of the project. Their contributions range from design decisions, technical guidance, roadmap, and even code contributions to the project.

**Comment by christian-kreuzberger-dtx** [comment]
I support

**Comment by johannes-b** [comment]
I support

**Comment by jetzlstorfer** [comment]
closing this issue as process is done
