### ISSUE TITLE
REQUEST: New membership approver for checkelmann

### ISSUE THREAD

**Issue by checkelmann** [keptn/community#45]
### Christian Heckelmann

@checkelmann 

### Requirements

- [X] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [X] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [X] I am actively contributing to 1 or more Keptn subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @jetzlstorfer 
- @johannes-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

https://github.com/keptn/keptn/commits?author=checkelmann
https://github.com/keptn/keptn/pulls?q=is%3Apr+author%3Acheckelmann+is%3Aclosed
https://github.com/keptn/go-utils/commits?author=checkelmann
https://github.com/keptn-sandbox/gitlab-service
https://github.com/keptn-sandbox/keptn-report
https://github.com/keptn-sandbox/dynatrace-synthetic-service

**Comment by jetzlstorfer** [comment]
I support
