### ISSUE TITLE
REQUEST: Membership Member for mowies

### ISSUE THREAD

**Issue by mowies** [keptn/community#47]
### GitHub Username

@mowies

### Membership level

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @johannes-b 
- @christian-kreuzberger-dtx 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project
https://github.com/keptn/keptn/commits?author=mowies
https://github.com/keptn/keptn/pulls?q=is%3Apr+author%3Amowies+is%3Aclosed+
https://github.com/keptn/keptn/issues/created_by/mowies

**Comment by christian-kreuzberger-dtx** [comment]
I support

**Comment by johannes-b** [comment]
I support!

**Comment by johannes-b** [comment]
Welcome, @mowies! Invite sent
