### ISSUE TITLE
REQUEST: Membership member for thisthat

### ISSUE THREAD

**Issue by thisthat** [keptn/community#48]
### GitHub Username

@thisthat

### Membership level

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @johannes-b 
- @warber 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- https://github.com/keptn/keptn/issues?q=commenter%3Athisthat+sort%3Aupdated-desc
- https://github.com/keptn/keptn/issues?q=is%3Aopen+is%3Aissue+author%3A%40me+sort%3Aupdated-desc
- https://github.com/keptn/get.keptn.sh/pulls?q=author%3Athisthat+sort%3Aupdated-desc+
- https://github.com/keptn/keptn.github.io/pulls?q=author%3Athisthat+sort%3Aupdated-desc+

**Comment by johannes-b** [comment]
I support

**Comment by warber** [comment]
I support

**Comment by johannes-b** [comment]
Welcome, @thisthat Invite sent
