### ISSUE TITLE
REQUEST: Membership approver for @mowies

### ISSUE THREAD

**Issue by mowies** [keptn/community#49]
### GitHub Username

@mowies

### Membership level

Approver

### Requirements (for approver, if applicable)

- [x] I am a reviewer of the codebase for at least 1 month
- [x] I am a reviewer for/or author of substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g., refactors/adds new functionality rather than one-line changes).
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @johannes-b 
- @bacherfl 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed: 
  - https://github.com/keptn/keptn/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3Amowies
  - https://github.com/keptn/go-utils/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3Amowies
- PRs authored:
  - https://github.com/keptn/keptn/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Amowies+
  - https://github.com/keptn/go-utils/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Amowies+
- Issues responded to:
  - https://github.com/keptn/keptn/issues?q=is%3Aissue+sort%3Aupdated-desc+involves%3Amowies+
  - https://github.com/keptn/go-utils/pulls?q=is%3Apr+sort%3Aupdated-desc+involves%3Amowies

**Comment by johannes-b** [comment]
I support!

**Comment by bacherfl** [comment]
I support

**Comment by johannes-b** [comment]
Closing as process is finished
