### ISSUE TITLE
REQUEST: Membership maintainer for @mowies

### ISSUE THREAD

**Issue by mowies** [keptn/community#50]
### GitHub Username

@mowies

### Membership level

Maintainer

### Requirements (for maintainer, if applicable)

- [x] I have deep understanding of the technical goals and direction of the subproject
- [x] I have deep understanding of the technical domain (specifically the language) of the subproject
- [x] I did sustained contributions to design and direction by doing all of:
  - [x] I am authoring and reviewing proposals
  - [x] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [x] I am identifying subtle or complex issues in designs and implementation PRs
- [x] I am directly contributing to the subproject through implementation and / or review
- [x] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @warber
- @jetzlstorfer 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs authored
  - https://github.com/keptn/keptn/pulls?q=is%3Apr+author%3Amowies
  - https://github.com/keptn/go-utils/pulls?q=is%3Apr+author%3Amowies
  - https://github.com/keptn/kubernetes-utils/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Amowies+
  - https://github.com/keptn/keptn.github.io/pulls?q=is%3Apr+author%3Amowies
- PRs reviewed
  - https://github.com/keptn/keptn/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3Amowies+
  - https://github.com/keptn/go-utils/pulls?q=is%3Apr+sort%3Aupdated-desc+reviewed-by%3Amowies+
- Issues responded to
  - https://github.com/keptn/keptn/issues?q=is%3Aissue+sort%3Aupdated-desc+involves%3Amowies

**Comment by warber** [comment]
I support

**Comment by jetzlstorfer** [comment]
I support

**Comment by jetzlstorfer** [comment]
@mowies has been added to @keptn/maintainers
