### ISSUE TITLE
REQUEST: Membership member for RealAnna

### ISSUE THREAD

**Issue by RealAnna** [keptn/community#54]
### GitHub Username

@RealAnna

### Membership level

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application

### Sponsors

- @thisthat 
- @johannes-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

-https://github.com/keptn/keptn/issues?q=commenter%3ARealAnna+sort%3Aupdated-desc+
-https://github.com/keptn/keptn/pulls?q=author%3ARealAnna+sort%3Aupdated-desc+

**Comment by johannes-b** [comment]
I support!

**Comment by thisthat** [comment]
I support!

**Comment by johannes-b** [comment]
@RealAnna please file a PR to add yourself to the members list here: https://github.com/keptn/keptn/blob/master/MAINTAINERS 

Then please link the PR here.

**Comment by RealAnna** [comment]
this one https://github.com/keptn/keptn/pull/5314

**Comment by johannes-b** [comment]
@RealAnna has been added to @keptn/members

**Comment by johannes-b** [comment]
Welcome, @RealAnna Invite sent
