### ISSUE TITLE
REQUEST: Membership member for robertjahn

### ISSUE THREAD

**Issue by robertjahn** [keptn/community#55]
### GitHub Username

robertjahn

### Membership level

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS.md) and referenced this issue in the PR

### Sponsors

- @johannes-b 
- @grabnerandi 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
- Issues responded to
- SIG projects I am involved with

**Comment by oleg-nenashev** [comment]
@robertjahn Hi! Did you have a chance to submit the request?

**Comment by robertjahn** [comment]
@oleg-nenashev -- I just added this PR for the addition
https://github.com/keptn/keptn/pull/6313

**Comment by oleg-nenashev** [comment]
@robertjahn is now in the list after https://github.com/keptn/keptn/pull/6450 . @thisthat @johannes-b would it be possible too grant Rob the required permissions so that we close this ticket?

**Comment by thisthat** [comment]
The invite has been sent. Welcome, @robertjahn!
