### ISSUE TITLE
REQUEST: Membership member for TannerGilbert

### ISSUE THREAD

**Issue by TannerGilbert** [keptn/community#58]
### GitHub Username

TannerGilbert

### Membership level

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR (https://github.com/keptn/keptn/pull/5899)

### Sponsors

- @jetzlstorfer
- @christian-kreuzberger-dtx

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- Locust
  - https://github.com/keptn-sandbox/locust-service/issues/50
  - https://github.com/keptn-sandbox/locust-service/pull/63
  - https://github.com/keptn-sandbox/locust-service/pull/72
- Podtato-Head
  - https://github.com/podtato-head/podtato-head/pull/65
  - https://github.com/podtato-head/podtato-head/pull/89
- Artifacthub
  - https://github.com/keptn-sandbox/artifacthub/pull/4
  - https://github.com/keptn-sandbox/artifacthub/pull/5
  - https://github.com/keptn-sandbox/artifacthub/pull/7
  - https://github.com/keptn-sandbox/artifacthub/pull/8
  - https://github.com/keptn-sandbox/artifacthub/pull/9
  - https://github.com/keptn-sandbox/artifacthub/pull/10
  -  https://github.com/keptn-sandbox/artifacthub/pull/11
  - https://github.com/keptn-sandbox/artifacthub/pull/12
  - https://github.com/keptn-sandbox/artifacthub/pull/13
  - https://github.com/keptn-sandbox/artifacthub/pull/14
  - https://github.com/keptn-sandbox/artifacthub/pull/16
  - https://github.com/keptn-sandbox/artifacthub/pull/17
  - https://github.com/keptn-sandbox/artifacthub/pull/18
  - https://github.com/keptn-sandbox/artifacthub/pull/20
  - https://github.com/keptn-sandbox/artifacthub/pull/23
  - https://github.com/keptn-sandbox/artifacthub/pull/24
  - https://github.com/keptn-sandbox/artifacthub/pull/26
  - https://github.com/keptn-sandbox/artifacthub/issues/21
  - https://github.com/keptn-sandbox/artifacthub/issues/25
- keptn.github.io
  - https://github.com/keptn/keptn.github.io/pull/933
  - https://github.com/keptn/keptn.github.io/pull/934
  - https://github.com/keptn/keptn.github.io/pull/937
  - https://github.com/keptn/keptn.github.io/pull/950

**Comment by jetzlstorfer** [comment]
I support

**Comment by christian-kreuzberger-dtx** [comment]
I approve

(please note that I would not consider Podtato-Head specific contributions in the Keptn context)

**Comment by thisthat** [comment]
Request send! Welcome @TannerGilbert!
