### ISSUE TITLE
REQUEST: Membership member for oleg-nenashev

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#61]
Submitting this application as aspiring Keptn community member. I do not have much code/issue contributions at the moment but I am working on it.

### GitHub Username

@oleg-nenashev

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

member

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR
### Requirements (for approver, if applicable)

- [ ] I am a reviewer of the codebase for at least 1 month
- [ ] I am a reviewer for/or author of substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g., refactors/adds new functionality rather than one-line changes).
- [ ] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project approver](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Requirements (for maintainer, if applicable)

- [ ] I have deep understanding of the technical goals and direction of the subproject
- [ ] I have deep understanding of the technical domain (specifically the language) of the subproject
- [ ] I did sustained contributions to design and direction by doing all of:
  - [ ] I am authoring and reviewing proposals
  - [ ] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [ ] I am identifying subtle or complex issues in designs and implementation PRs
- [ ] I am directly contributing to the subproject through implementation and / or review
- [ ] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [ ] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [ ] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @jetzlstorfer 
- @johannes-b 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored: 
  - GitHub org metadata, now in Sandbox for review: https://github.com/keptn-sandbox/.github
- Issues responded to
  - Issues created by me: https://github.com/search?q=is%3Aissue+org%3Akeptn+author%3Aoleg-nenashev
- SIG projects I am involved with: CD SIG Events and CD Events (CDF Upstream specification, includes Keptn Events)

**Comment by johannes-b** [comment]
I support!

**Comment by jetzlstorfer** [comment]
I support

**Comment by johannes-b** [comment]
https://github.com/keptn/keptn/pull/6256 used instead of https://github.com/keptn/keptn/pull/6236

**Comment by johannes-b** [comment]
Request send! Welcome @oleg-nenashev!
