### ISSUE TITLE
Create a .github repository for org-wide configuration management

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#64]
It would be nice to have a .github repository so that we could create content similar to https://github.com/keptn-sandbox/.github . I'd like to also use the repo for the following:

* Modify the Keptn organization profile page
* Add global CONTRIBUTING, CONDUCT and SECURITY metadata
* TBD - move issue and pull request templates to the repo

## Stakeholders

@johannes-b @thisthat

**Comment by johannes-b** [comment]
Please find the repo here: https://github.com/keptn/.github ;)

**Comment by oleg-nenashev** [comment]
Thank you!

**Comment by DavidPHirsch** [comment]
Hi, I believe we can close this issue. the .github repository exists

**Comment by thisthat** [comment]
We are working on per-repo contributing guide to fit the needs of each individual component
