### ISSUE TITLE
Grant @oleg-nenashev triage permissions in this repo

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#66]
Hello, I would like to help with community management and contributor onboarding for Keptn. To do so, it would be nice to have Triage or Write permissions so that I could manage this repository and gradually extend it. In particular, I would like to introduce the community roadmap including topics like governance, community management, events, etc., etc. This roadmap would complement the technical roadmap for the project.

## Stakeholders / sponsors

* @johannes-b 
* @grabnerandi 
* @AloisReitbauer 
* @thisthat

**Comment by thisthat** [comment]
I support this

**Comment by johannes-b** [comment]
I support this too!

The invite to first become a member is sent out. :)

**Comment by oleg-nenashev** [comment]
Request accepted @johannes-b !

**Comment by oleg-nenashev** [comment]
I have access now, thanks!
