### ISSUE TITLE
Keptn in Google Summer of Code 2022

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#69]
It would be nice to have Keptn participating in [Google Summer of Code 2022](https://summerofcode.withgoogle.com/) so that we could have a few students working on new Keptn integrations or some core features that do not stand on the critical path of the Keptn roadmap. It is good for community bonding, and hopefully for new contributor onboarding too.

Project applications will start in mid-January

## Potential project ideas

This list is based on the discussions with Keptn users and contributors. Please feel free to propose your ideas in the comments!

* Better GitHub Integration in Keptn
  * Use-cases: GitHub App Authentication, Reporting to Checks and Deployment API, GitHub Actions executor service
* Integration service for [k6](https://k6.io/)
  * Use-case: Performance testing as a part of Keptn Quality Gates, similar to the existing JMeter service
* Jenkinsfile Executor Service for Keptn
  * Executing Jenkins Pipelines as a service in Keptn. Based on [Jenkinsfile Runner](https://github.com/jenkinsci/jenkinsfile-runner) 
  * Potential mentor(s): Oleg Nenashev
* Keptn Plugin for [Backstage](https://backstage.io/)
  * See keptn/integrations#19 
  * Potential mentor(s): Oleg Nenashev
* GitOps for Keptn
  * See https://github.com/keptn/enhancement-proposals/pull/67 
* // Add your ideas in the comments!

## References

* https://summerofcode.withgoogle.com/

**Comment by thschue** [comment]
The GSoC Projects are done, therefore this can be closed

**Comment by agardnerIT** [comment]
# Looking For GSoC 2023? Go Here >> https://github.com/keptn/community/issues/216
