### ISSUE TITLE
Docs project in GSoD 2022 or LFX Mentorship

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#70]
Google Season of Docs is a new program focused on documentation mentorship programs. It would be great to have a mentee working on the documentation specifically

**Comment by mehabhalodiya** [comment]
> Google Season of Code is a new program focused on documentation mentorship programs.

@oleg-nenashev Needs to be: Google Season of Docs

**Comment by oleg-nenashev** [comment]
@mehabhalodiya fixed, thanks

**Comment by thschue** [comment]
The 2022 program is over, therefore closing this issue
