### ISSUE TITLE
Unconsistency between Keptn maintainer lists

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#73]
The Keptn community uses https://github.com/keptn/keptn/blob/master/MAINTAINERS as a source of truth for maintainers. At the same time the CNCF uses https://github.com/cncf/foundation/blob/master/project-maintainers.csv#L506 which does not include recently added maintainers.

It would be great to fix the listing on the CNCF side

**Comment by thschue** [comment]
In the meanwhile, the two files are consistent and we add new maintainers automatically to the CNCF List
