### ISSUE TITLE
Create a new #keptn channel on the Kubernetes Slack

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#74]
### Proposal

Many end users are present in Kubernetes Slack workspace and do not want to join project-specific Slack workspace. It would be nice if we go directly to our end users and create a Slack channel on Kubernetes. Likely just `#keptn` for anything about Keptn, or `#keptn-users` and `#keptn-dev` for user and developer communities

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by jetzlstorfer** [comment]
Hi @oleg-nenashev ! 
we already have a channel in the CNCF Slack workspace (slack.cncf.io) which you can find [here](https://cloud-native.slack.com/archives/C017GAX90GM). Personally, I would not go for another Slack workspace in the [Kubernetes slack](https://slack.k8s.io/), I feel that many of our endusers and community can be found in the CNCF Slack. However, that is just my personal opinion :)

**Comment by thschue** [comment]
I agree to @jetzlstorfer here, at the moment, the CNCF and own slack spaces should be enough.
