### ISSUE TITLE
🛣️ Community Roadmap

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#76]
In addition to the project's technical roadmap, there is also roadmap for growing the Keptn user and developer community. It is a part of the main [Keptn Roadmap](https://github.com/orgs/keptn/projects/10). Use [this filter](https://github.com/orgs/keptn/projects/10/views/3) to access only the community related items.

P.S: This is a placeholder issues.

**Comment by DavidPHirsch** [comment]
Listed as a placeholder issue. I think we can close
