### ISSUE TITLE
Keptn Community Day at Kubecon Valencia

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#78]
### Proposal

As discussed in the chats, it would be great to have a Keptn focused event during Kubecon in Valencia, May 2022. The idea is to make it a user-focused event so that we leverage the proximity of Kubecon and the potential Keptn Adopters there

* Full-day or half-day event, preferably in person in Valencia.
* Target audience: Current and potential Keptn adopters. Up to 50/100 visitors or whatever the local COVID rules / venue capacity are.
* The event is community focused and vendor neutral. It would be great to have multiple company/information sponsors
* The main goal is to discuss/present Keptn for users, including success stories, case studies, and the project roadmap
* It would be nice to have a panel session with maintainers and user advisory board at this event
* There could be a collocated Keptn intro workshop for newcomers. We did such for Jenkins summits, and it was a nice format
* Of course some kind of Apero and networking is needed. Maybe a happy hour to celebrate Keptn incubation in the CNCF. See #81 

### References

* Overview slidedeck: https://docs.google.com/presentation/d/1SzwJD_1f9ufy_hbHGJD8N6nSKtuj80ysI_Srmx-Or5M/edit?usp=sharing

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by oleg-nenashev** [comment]
I created  `#keptn-community-day-kubecon-valencia` for initial discussion of the Keptn Community Day during Kubecon Valencia timeframe in May. Keeping the channel private for now until we have the initial plan/framework, and actually confirm the event. If you are interested to participate in early stages, please respond to this thread.

**Comment by oleg-nenashev** [comment]
Overview slidedeck is here: https://docs.google.com/presentation/d/1SzwJD_1f9ufy_hbHGJD8N6nSKtuj80ysI_Srmx-Or5M/edit?usp=sharing

**Comment by bradmccoydev** [comment]
Closing as this event has passed
