### ISSUE TITLE
RFE: Adopt a Community analytics tool in the project

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#80]
### Proposal

It wpould be nice to adopt LFX Insights as a source of community metrics. There is a project here: https://insights.lfx.linuxfoundation.org/projects/cncf%2Fkeptn/dashboard , but currently it is disabled. We need to take ownership of it and re-enable

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by oleg-nenashev** [comment]
Quick update regarding the tooling side, the Linux Foundation does not longer onboard new projects to [LFX Insights](https://insights.lfx.linuxfoundation.org/). There is no confirmed ETA when they are back to business, the optimistic ETA is March. If we want to introduce community analytics before this time, we will need to consider other options like [Bitergia Cauldron](https://cauldron.io/).

**Comment by DavidPHirsch** [comment]
adopted common room
