### ISSUE TITLE
Add @oleg-nenashev to keptn-contrib

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#85]
It would be great to be added to https://github.com/keptn-contrib as organization member so that my reviews could be requested and so that I could probably help with GitHub organization management.

### GitHub Username

@oleg-nenashev

### Membership level

Membership level according to https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md

`member`

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @grabnerandi 
- @johannes-b 
- @thisthat

**Comment by thisthat** [comment]
I support

**Comment by johannes-b** [comment]
I support

**Comment by oleg-nenashev** [comment]
Thanks! Now I need someone to actually add me there

**Comment by christian-kreuzberger-dtx** [comment]
I will handle that.

**Comment by oleg-nenashev** [comment]
I believe it is fixed now. Thanks @christian-kreuzberger-dtx !
