### ISSUE TITLE
YouTube Account access issues

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#86]
Looks like we have an issue with our brand account. CC @jetzlstorfer 

## TODOs

- [x] Fix the issue
- [ ] Ensure we do not have this issue again

## Notes

![image](https://user-images.githubusercontent.com/3000480/146516936-04925cba-d289-4e55-ab8d-a37bca050853.png)

**Comment by oleg-nenashev** [comment]
First two appeals to YouTube were rejected. Calling the cavalry

**Comment by thisthat** [comment]
We have access to our YT account. Closing the issue
