### ISSUE TITLE
Security process improvements

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#87]
### Proposal

Currently the security process is documented [here](https://github.com/keptn/keptn/blob/master/SECURITY.md). It borrows a lot from https://kubernetes.io/security/ but at the same time there are some issues in it:

* How are the security issues tracked?
* How does one join the "Security group"? Currently there 4 Keptn maintainers on the list, but there are no groups or Slack channels for coordination
* What are the rules for announcing security vulnerabilities on https://keptn.sh/docs/news/vulnerability_bulletins/ ? Who is expected to prepare them and how do 
* What is our CNA, and how are CVEs are issued for the project? 
* Does the project follow best secure software supply chain practices?
* Is the security process aligned with Core Infrastructure Initiative requirements (prerequisite for graduation)?

### References

* Keptn security process: https://github.com/keptn/keptn/blob/master/SECURITY.md
* Keptn Security BBulletins: https://keptn.sh/docs/news/vulnerability_bulletins/
* https://kubernetes.io/security/
* CII Best Practices: https://www.coreinfrastructure.org/programs/best-practices-program/

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by christian-kreuzberger-dtx** [comment]
I can answer two things here:

> How are the security issues tracked?

IMHO they are not tracked (very well) at the moment.
Maybe we can handle via a CNCF issue tracker?

> What are the rules for announcing security vulnerabilities on https://keptn.sh/docs/news/vulnerability_bulletins/ ? Who is expected to prepare them and how do

IMHO it is the responsibility of [Security Contacts](https://github.com/keptn/keptn/blob/master/SECURITY.md#security-contacts) to do that.

If we have concrete improvements, I'm happy to sponsor them.

**Comment by oleg-nenashev** [comment]
> If we have concrete improvements, I'm happy to sponsor them.

Yes, there will be. I will do a retrospective for log4shell, and then submit proposals
