### ISSUE TITLE
APAC friendly Community meetings

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#88]
### Proposal

It would be nice to have Community meetings in an APAC friendly time slot. Currently the meetings happen at 4:00 p.m. UTC, and it's not convenient for all contributors.

As discussed in slack, it would be nice to have regular meetings, for example at 8:00 or 9:00 a.m. UTC so that APAC and EMEA could participate

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by agardnerIT** [comment]
I support

**Comment by oleg-nenashev** [comment]
The next meeting will take place on Wed, Jan 19, 9AM UTC. The announcement is coming soon

**Comment by oleg-nenashev** [comment]
Meetings are created and now announced on 

* https://community.cncf.io/keptn-community/
* https://keptn.sh/community/
