### ISSUE TITLE
REQUEST: Maintainer status for @oleg-nenashev

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#91]
I would like to request the maintainer status in Keptn. I have been an active contributor since July 2021, and currently I am helping with community management and Keptn growth. I do not contribute much to the Keptn production codebase but I focus on other areas: public roadmap, issue backlog, documentation and tutorials, Keptn adoption, contributor guidelines, community marketing, etc. All of that is an important part of the Keptn community!

My main use-cases for the maintainer status are:

- GitHub org and repository administration so that I can help other maintainers with processing requests and improving the community
- Access to the CNCF support portal o that I can handle CNCF interaction on my own for the ecosystem, e.g. community.cncf.io, Maintainer List, LFX Mentorship, LFX Insights, Slack, Core Infrastructure Initiative, etc.
- Representing the Keptn project officially in the CNCF and other communities/organizations, e.g. for Keptn incubation or technical partnerships

### GitHub Username

@oleg-nenashev

### Membership level

maintainer

### Requirements (for member)

- [x] I have reviewed the community membership guidelines (https://github.com/keptn/community/blob/master/COMMUNITY_MEMBERSHIP.md)
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Keptn Slack channel](http://slack.keptn.sh/)
- [x] I am actively contributing to 1 or more Keptn subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to 2 sponsors (approvers or maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project member](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Requirements (for approver, if applicable)

- [x] I am a reviewer of the codebase for at least 1 month
- [x] I am a reviewer for/or author of substantial PRs to the codebase, with the definition of substantial subject to the maintainer's discretion (e.g., refactors/adds new functionality rather than one-line changes).
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project approver](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Requirements (for maintainer, if applicable)

- [x] I have deep understanding of the technical goals and direction of the subproject
- [x] I have deep understanding of the technical domain (specifically the language) of the subproject
- [x] I did sustained contributions to design and direction by doing all of:
  - [x] I am authoring and reviewing proposals
  - [x] I am initiating, contributing, and resolving discussions (e-mails, GitHub issues, meetings)
  - [x] I am identifying subtle or complex issues in designs and implementation PRs
- [x] I am directly contributing to the subproject through implementation and / or review
- [x] I am aligning with the overall project goals, specifications, and design principles. I am bringing general questions and requests to the discussions as part of the specifications project.
- [x] I have spoken to 2 sponsors (maintainers) ahead of this application, and they have agreed to sponsor my application
- [x] I have filed a PR to add myself as [project maintainer](https://github.com/keptn/keptn/blob/master/MAINTAINERS) and referenced this issue in the PR

### Sponsors

- @grabnerandi 
- @AloisReitbauer 
- @johannes-b 
- @thisthat 
- @christian-kreuzberger-dtx 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors' confirmation before submitting the request.

### List of contributions to the Keptn project

- PRs reviewed / authored
  - Filed pull requests: https://github.com/search?q=org%3Akeptn+org%3Akeptn-sandbox+org%3Akeptn-integrations+is%3Apr+author%3Aoleg-nenashev&type=issues . Key authored ones:
    -  https://github.com/keptn/keptn/pull/6405
    - https://github.com/keptn/keptn.github.io/pull/989
    - https://github.com/keptn/tutorials/pull/209
    - https://github.com/keptn/community/pull/77
  - Reviewed PRs: https://github.com/search?q=org%3Akeptn+org%3Akeptn-sandbox+org%3Akeptn-integrations+is%3Apr+reviewed-by%3Aoleg-nenashev&type=issues
- Issues responded to
  - Keptn RFEs relevant to the community feedback and requests
  - Keptn community roadmap on https://github.com/keptn/community/issues
  - User support in the `#help` channel
- SIG projects I am involved with
  - CDF: Events SIG (Keptn Events is a part of it), Interoperability SIG, TOC, Governing Board
  - CNCF: [TAG App Delivery](https://github.com/cncf/tag-app-delivery)
  - Many [Jenkins SIGs](https://www.jenkins.io/sigs)

**Comment by grabnerandi** [comment]
I support

**Comment by thisthat** [comment]
I support

**Comment by thisthat** [comment]
I have sent you an invitation! Thank you for your contributions @oleg-nenashev 
Please, update the [MAINTAINERS ](https://github.com/keptn/keptn/blob/master/MAINTAINERS) file so I can close this issue

**Comment by jetzlstorfer** [comment]
I support

**Comment by oleg-nenashev** [comment]
FTR https://github.com/keptn/keptn/pull/6522

**Comment by johannes-b** [comment]
I support!

**Comment by christian-kreuzberger-dtx** [comment]
I support!

**Comment by johannes-b** [comment]
Great to have you as maintainer! 

@oleg-nenashev has been added to @keptn/maintainers

**Comment by oleg-nenashev** [comment]
Thanks all for your support!
