### ISSUE TITLE
Restore access to the keptn organization on NPM

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/community#92]
There is a `@keptn` account on NPM which includes a few old projects, e.g. npmjs.com/package/@keptn/pitometer . It was created around 2 years ago, and Daniel Khan is the last one to upload a new package there. I assume Daniel is an owner though not 100% sure. 

Now @thschue needs it to deploy a few packages for a Keptn Sandbox project. We should regain access

### Sponsors

- (at)sponsor-1
- (at)sponsor-2

### Checklist

- [ ] The idea is brought up for a discussion in a relevant Keptn Slack channel (use `#keptn-project` by default)
- [ ] Each sponsor should reply to this issue with the comment "*I support*".

**Comment by thschue** [comment]
@DavidPHirsch got access and I can push to NPM, therefore solved.
